# SPDX-FileCopyrightText: 2026 Curtis Galloway
# SPDX-License-Identifier: Apache-2.0
"""Tests for scripts/resolve_pins.py. All network access goes through a stub Upstream."""

from __future__ import annotations

import base64
import hashlib
import json
import os
import subprocess
from pathlib import Path

import pytest

import resolve_pins as rp

V = "33.20260927.4.1"
FX = "b5274053cc0f1ba03cd0902a3da575ac9c31c152"
INTEG = "1463df67e630ab75428ad5731ab1c24dd5dce1a9"
BUILDS = ["8669503301662913841", "8669503301662913825", "8669503301662913777"]
RUST_PIN = "git_revisions:c26ce708de5d14682647895d2f3caf38f70b5aa6,3493720eca95cf844a8d7e58fdd12e0e5644e7d0"
HOST_ID = "3a8ffdbed3f78ba359e5e9a4677a5d27c8e13d9c4822243bf78b16a57acb225f"
TARGET_ID = "4fe0f40e20ce02113705648c7123afcee4294c7d5e98459bf1e5c0204f07d603"
IDK_CIPD_ID = "41d82a3f4dbf718a5141040d36e463b218a49c97837b964a5f2a86ab6624a8a9"
RULES_ID = "8d346b9a21a6c3c0d4e6ffc40e9ef0f81e9545dd75040b068d4fa09d74f54845"
IDK_BYTES = b"not really a tarball"
CARGO_LOCK = b"# This file is automatically @generated by Cargo.\nversion = 4\n"

TOOLCHAIN_XML = b"""<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <packages>
    <package name="fuchsia/third_party/lldb/${platform}"
             version="git_revision:0f61051f541a5b8cfce25c84262dfdbadb9ca688"
             platforms="linux-amd64,mac-amd64"
             path="prebuilt/third_party/lldb/{{.OS}}-{{.Arch}}"/>
    <package name="fuchsia/third_party/rust/host/${platform}"
             version="%(pin)s"
             platforms="linux-amd64,linux-arm64,mac-amd64,mac-arm64,windows-amd64"
             path="prebuilt/third_party/rust/{{.OS}}-{{.Arch}}"/>
    <package name="fuchsia/third_party/rust/target/fuchsia"
             version="%(pin)s"
             platforms="linux-amd64,linux-arm64,mac-amd64,mac-arm64"
             path="prebuilt/third_party/rust/{{.OS}}-{{.Arch}}"/>
    <package name="fuchsia/third_party/rust/target/aarch64-apple-darwin"
             version="%(pin)s"
             platforms="linux-amd64,linux-arm64,mac-amd64,mac-arm64"
             path="prebuilt/third_party/rust/{{.OS}}-{{.Arch}}"/>
  </packages>
</manifest>
""" % {b"pin": RUST_PIN.encode()}

GCS = "https://storage.googleapis.com"
PB_URL = f"{GCS}/fuchsia/development/{V}/product_bundles.json"
IDK_URL = f"{GCS}/fuchsia/development/{V}/sdk/linux-amd64/core.tar.gz"
IDK_META_URL = f"{GCS}/storage/v1/b/fuchsia/o/development%2F{V}%2Fsdk%2Flinux-amd64%2Fcore.tar.gz"


def sm_url(build: str) -> str:
    return f"{GCS}/fuchsia-public-artifacts-release/builds/{build}/source_manifest.json"


def source_manifest(fx: str = FX, integ: str = INTEG) -> dict:
    return {"directories": {
        ".": {"git_checkout": {"repo_url": "https://fuchsia.googlesource.com/fuchsia", "revision": fx}},
        "integration": {"git_checkout": {"repo_url": "https://example.invalid/integration", "revision": integ}},
    }}


class Stub:
    """An Upstream whose replies are plain dicts, so each test can break one lookup."""

    def __init__(self):
        self.gets: dict[str, object] = {
            PB_URL: [
                {"name": n, "product_version": V,
                 "transfer_manifest_url": f"gs://fuchsia-public-artifacts-release/builds/{b}/product_bundles/{n}/transfer.json"}
                for b, n in zip(BUILDS, ["core.vim3", "core.x64", "minimal.arm64"])
            ],
            **{sm_url(b): source_manifest() for b in BUILDS},
            IDK_META_URL: {"size": str(len(IDK_BYTES)),
                           "md5Hash": base64.b64encode(hashlib.md5(IDK_BYTES).digest()).decode()},
        }
        # (package, version) -> instance hex digest, or an int HTTP status to fail with.
        self.cipd: dict[tuple[str, str], object] = {
            ("fuchsia/sdk/core/linux-amd64", f"version:{V}"): IDK_CIPD_ID,
            ("fuchsia/third_party/rust/host/linux-amd64", RUST_PIN): HOST_ID,
            ("fuchsia/third_party/rust/target/fuchsia", RUST_PIN): TARGET_ID,
            ("fuchsia/development/rules_fuchsia", f"git_revision:{INTEG}"): RULES_ID,
            ("fuchsia/development/rules_fuchsia", f"version:{V}"): RULES_ID,
        }
        self.tags: dict[tuple[str, str], list[dict]] = {
            ("fuchsia/sdk/core/linux-amd64", IDK_CIPD_ID): [
                {"key": "git_revision", "value": INTEG}, {"key": "version", "value": V}],
        }
        self.digests: dict[str, object] = {IDK_URL: IDK_BYTES}
        self.git: dict[str, object] = {"manifests/toolchain": TOOLCHAIN_XML,
                                       "third_party/rust_crates/Cargo.lock": CARGO_LOCK}
        self.git_error: str | None = None
        self.calls: list[tuple] = []

    def get(self, url):
        self.calls.append(("get", url))
        reply = self.gets.get(url, 404)
        if isinstance(reply, int):
            raise rp.FetchError(f"GET {url}: HTTP {reply}", reply)
        return reply if isinstance(reply, bytes) else json.dumps(reply).encode()

    def post_json(self, url, payload):
        self.calls.append(("post", url, json.dumps(payload, sort_keys=True)))
        assert url.startswith("https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/")
        method, package = url.rsplit("/", 1)[1], payload["package"]
        if method == "ResolveVersion":
            reply = self.cipd.get((package, payload["version"]), 404)
            if isinstance(reply, int):
                raise rp.FetchError(f"HTTP {reply} no such tag", reply)
            if isinstance(reply, bytes):  # a raw, possibly malformed, reply body
                return b")]}'\n" + reply
            body = {"package": package, "instance": {"hashAlgo": "SHA256", "hexDigest": reply}}
        elif method == "DescribeInstance":
            assert payload["describeTags"] is True
            tags = self.tags.get((package, payload["instance"]["hexDigest"]), [])
            if isinstance(tags, bytes):
                return b")]}'\n" + tags
            body = {"instance": payload["instance"], "tags": tags}
        else:
            raise AssertionError(method)
        return b")]}'\n" + json.dumps(body).encode()

    def digest(self, url):
        self.calls.append(("digest", url))
        data = self.digests.get(url, 404)
        if isinstance(data, Exception):
            raise data
        if isinstance(data, int):
            raise rp.FetchError(f"GET {url}: HTTP {data}", data)
        return rp.Digest(hashlib.sha256(data).hexdigest(), hashlib.md5(data).hexdigest(), len(data))

    def git_show(self, repo, revision, path):
        # Like LiveUpstream: a fetch failure or a missing path raises FetchError.
        self.calls.append(("git", repo, revision, path))
        assert repo == "https://fuchsia.googlesource.com/fuchsia"
        if self.git_error:
            raise rp.FetchError(self.git_error)
        if path not in self.git:
            raise rp.FetchError(f"git cat-file -p {revision}:{path}: fatal: path '{path}' does not exist")
        return self.git[path]


def run(stub: Stub, out: Path, version: str = V) -> int:
    return rp.main([version, "--out", str(out)], upstream=stub)


# --- happy path ----------------------------------------------------------------


def test_happy_path_writes_every_field_with_a_source(tmp_path):
    out = tmp_path / "overlay.lock.json"
    assert run(Stub(), out) == 0
    lock = json.loads(out.read_text())
    assert sorted(lock) == ["bazel_sdk", "cargo_lock_sha256", "fuchsia_revision", "integration_revision",
                            "rules_fuchsia", "rust_host", "rust_target", "sdk_version"]
    for field, entry in lock.items():
        assert entry["value"], field
        assert entry["source"] and all(isinstance(s, str) and s for s in entry["source"]), field
    assert lock["sdk_version"] == {"value": V, "source": [PB_URL]}
    assert lock["fuchsia_revision"] == {"value": FX, "source": sorted(sm_url(b) for b in BUILDS)}
    assert lock["integration_revision"]["value"] == INTEG
    assert lock["integration_revision"]["source"][-1] == (
        f"https://chrome-infra-packages.appspot.com/p/fuchsia/sdk/core/linux-amd64/+/version:{V}")
    assert lock["rust_host"] == {
        "package": "fuchsia/third_party/rust/host/linux-amd64",
        "value": HOST_ID,
        "source": [f"https://fuchsia.googlesource.com/fuchsia {FX}:manifests/toolchain",
                   f"https://chrome-infra-packages.appspot.com/p/fuchsia/third_party/rust/host/linux-amd64/+/{RUST_PIN}"],
    }
    assert lock["rust_target"]["package"] == "fuchsia/third_party/rust/target/fuchsia"
    assert lock["rust_target"]["value"] == TARGET_ID
    assert lock["bazel_sdk"] == {"url": IDK_URL, "value": hashlib.sha256(IDK_BYTES).hexdigest(), "source": [IDK_URL]}
    assert lock["rules_fuchsia"] == {
        "package": "fuchsia/development/rules_fuchsia",
        "value": RULES_ID,
        "source": [f"https://chrome-infra-packages.appspot.com/p/fuchsia/development/rules_fuchsia/+/git_revision:{INTEG}"],
    }
    assert lock["cargo_lock_sha256"] == {
        "value": hashlib.sha256(CARGO_LOCK).hexdigest(),
        "source": [f"https://fuchsia.googlesource.com/fuchsia {FX}:third_party/rust_crates/Cargo.lock"],
    }


def test_output_is_sorted_indented_json_with_trailing_newline(tmp_path):
    out = tmp_path / "lock.json"
    assert run(Stub(), out) == 0
    data = out.read_bytes()
    assert data.endswith(b"}\n") and not data.endswith(b"\n\n")
    assert data == (json.dumps(json.loads(data), indent=2, sort_keys=True) + "\n").encode()


def test_git_is_read_at_the_resolved_revision_only(tmp_path):
    stub = Stub()
    assert run(stub, tmp_path / "lock.json") == 0
    git_calls = [c for c in stub.calls if c[0] == "git"]
    assert git_calls == [
        ("git", "https://fuchsia.googlesource.com/fuchsia", FX, "manifests/toolchain"),
        ("git", "https://fuchsia.googlesource.com/fuchsia", FX, "third_party/rust_crates/Cargo.lock"),
    ]


def test_no_request_goes_to_gitiles_or_carries_credentials(tmp_path):
    stub = Stub()
    assert run(stub, tmp_path / "lock.json") == 0
    urls = [c[1] for c in stub.calls]
    assert all(u.startswith("https://") for u in urls)
    assert not any("/+/" in u or "/+log" in u for u in urls if "googlesource" in u)
    assert not any("@" in u.split("//", 1)[1].split("/", 1)[0] for u in urls)


# --- determinism ------------------------------------------------------------------


def test_same_stubs_give_same_bytes(tmp_path):
    a, b = tmp_path / "a.json", tmp_path / "b.json"
    assert run(Stub(), a) == 0 and run(Stub(), b) == 0
    assert a.read_bytes() == b.read_bytes()


def test_product_bundle_order_does_not_change_output(tmp_path):
    a, b = tmp_path / "a.json", tmp_path / "b.json"
    assert run(Stub(), a) == 0
    stub = Stub()
    stub.gets[PB_URL] = list(reversed(stub.gets[PB_URL]))
    assert run(stub, b) == 0
    assert a.read_bytes() == b.read_bytes()


def test_rerun_over_existing_lock_is_byte_identical(tmp_path):
    out = tmp_path / "lock.json"
    assert run(Stub(), out) == 0
    first = out.read_bytes()
    assert run(Stub(), out) == 0
    assert out.read_bytes() == first


# --- failure paths: each exits non-zero, names the field, and leaves the lock alone ---

FAILURES = {
    "unknown version (product_bundles.json 404)":
        ("sdk_version", lambda s: s.gets.pop(PB_URL)),
    "empty product bundle list":
        ("sdk_version", lambda s: s.gets.__setitem__(PB_URL, [])),
    "bundle for another version":
        ("sdk_version", lambda s: s.gets[PB_URL][1].__setitem__("product_version", "33.20260927.3.1")),
    "bundle without a build id":
        ("sdk_version", lambda s: s.gets[PB_URL][0].__setitem__("transfer_manifest_url", "gs://x/y.json")),
    "source manifest 404":
        ("fuchsia_revision", lambda s: s.gets.pop(sm_url(BUILDS[1]))),
    "source manifest malformed":
        ("fuchsia_revision", lambda s: s.gets.__setitem__(sm_url(BUILDS[1]), {"directories": {}})),
    "source manifest not JSON":
        ("fuchsia_revision", lambda s: s.gets.__setitem__(sm_url(BUILDS[1]), b"<html>")),
    "builds disagree on fuchsia.git":
        ("fuchsia_revision", lambda s: s.gets.__setitem__(sm_url(BUILDS[2]), source_manifest(fx="0" * 40))),
    "'.' is not fuchsia.git":
        ("fuchsia_revision", lambda s: s.gets[sm_url(BUILDS[0])]["directories"]["."]["git_checkout"]
         .__setitem__("repo_url", "https://example.invalid/other")),
    "builds disagree on integration":
        ("integration_revision", lambda s: s.gets.__setitem__(sm_url(BUILDS[2]), source_manifest(integ="1" * 40))),
    "IDK not in CIPD":
        ("integration_revision", lambda s: s.cipd.pop(("fuchsia/sdk/core/linux-amd64", f"version:{V}"))),
    "IDK tag is another integration commit":
        ("integration_revision", lambda s: s.tags.__setitem__(
            ("fuchsia/sdk/core/linux-amd64", IDK_CIPD_ID), [{"key": "git_revision", "value": "2" * 40}])),
    "IDK has no git_revision tag":
        ("integration_revision", lambda s: s.tags.__setitem__(("fuchsia/sdk/core/linux-amd64", IDK_CIPD_ID), [])),
    "git fetch fails":
        ("rust_host", lambda s: setattr(s, "git_error", "git fetch: fatal: remote error")),
    "manifests/toolchain missing":
        ("rust_host", lambda s: s.git.pop("manifests/toolchain")),
    "manifests/toolchain not XML":
        ("rust_host", lambda s: s.git.__setitem__("manifests/toolchain", b"<manifest")),
    "host package not pinned":
        ("rust_host", lambda s: s.git.__setitem__("manifests/toolchain", TOOLCHAIN_XML.replace(
            b"rust/host/${platform}", b"rust/hostx/${platform}"))),
    "host package not for linux-amd64":
        ("rust_host", lambda s: s.git.__setitem__("manifests/toolchain", TOOLCHAIN_XML.replace(
            b'platforms="linux-amd64,linux-arm64,mac-amd64,mac-arm64,windows-amd64"', b'platforms="mac-arm64"'))),
    "target package not pinned":
        ("rust_target", lambda s: s.git.__setitem__("manifests/toolchain", TOOLCHAIN_XML.replace(
            b"rust/target/fuchsia\"", b"rust/target/fuchsiax\""))),
    "host CIPD 404":
        ("rust_host", lambda s: s.cipd.pop(("fuchsia/third_party/rust/host/linux-amd64", RUST_PIN))),
    "target CIPD 404":
        ("rust_target", lambda s: s.cipd.pop(("fuchsia/third_party/rust/target/fuchsia", RUST_PIN))),
    "target CIPD ambiguous tag (HTTP 400)":
        ("rust_target", lambda s: s.cipd.__setitem__(("fuchsia/third_party/rust/target/fuchsia", RUST_PIN), 400)),
    "host CIPD reply is not a SHA-256 instance":
        ("rust_host", lambda s: s.cipd.__setitem__(("fuchsia/third_party/rust/host/linux-amd64", RUST_PIN), "abc")),
    "Cargo.lock missing":
        ("cargo_lock_sha256", lambda s: s.git.pop("third_party/rust_crates/Cargo.lock")),
    "Cargo.lock empty":
        ("cargo_lock_sha256", lambda s: s.git.__setitem__("third_party/rust_crates/Cargo.lock", b"")),
    "product_bundles.json is an object":
        ("sdk_version", lambda s: s.gets.__setitem__(PB_URL, {"bundles": []})),
    "product bundle entry is a string":
        ("sdk_version", lambda s: s.gets[PB_URL].__setitem__(0, "core.x64")),
    "source manifest git_checkout is a string":
        ("fuchsia_revision", lambda s: s.gets[sm_url(BUILDS[0])]["directories"]["."].__setitem__("git_checkout", "x")),
    "source manifest revision is a number":
        ("fuchsia_revision", lambda s: [s.gets.__setitem__(sm_url(b), source_manifest(fx=7)) for b in BUILDS]),
    "IDK metadata is a list":
        ("bazel_sdk", lambda s: s.gets.__setitem__(IDK_META_URL, [1, 2])),
    "IDK download fails mid-stream":
        ("bazel_sdk", lambda s: s.digests.__setitem__(IDK_URL, rp.FetchError("GET x: IncompleteRead: 5 bytes read"))),
    "IDK metadata 404":
        ("bazel_sdk", lambda s: s.gets.pop(IDK_META_URL)),
    "IDK metadata lacks md5":
        ("bazel_sdk", lambda s: s.gets.__setitem__(IDK_META_URL, {"size": "3"})),
    "IDK download 404":
        ("bazel_sdk", lambda s: s.digests.pop(IDK_URL)),
    "IDK download truncated":
        ("bazel_sdk", lambda s: s.digests.__setitem__(IDK_URL, IDK_BYTES[:-1])),
    "IDK download corrupted":
        ("bazel_sdk", lambda s: s.digests.__setitem__(IDK_URL, IDK_BYTES.upper())),
    "host CIPD reply is a list":
        ("rust_host", lambda s: s.cipd.__setitem__(("fuchsia/third_party/rust/host/linux-amd64", RUST_PIN), b"[]")),
    "host CIPD instance is a string":
        ("rust_host", lambda s: s.cipd.__setitem__(("fuchsia/third_party/rust/host/linux-amd64", RUST_PIN),
                                                  b'{"instance": "abc"}')),
    "IDK CIPD tags is an object":
        ("integration_revision", lambda s: s.tags.__setitem__(("fuchsia/sdk/core/linux-amd64", IDK_CIPD_ID),
                                                             b'{"tags": {"git_revision": "x"}}')),
    "IDK CIPD tag entry is a string":
        ("integration_revision", lambda s: s.tags.__setitem__(("fuchsia/sdk/core/linux-amd64", IDK_CIPD_ID),
                                                             b'{"tags": ["git_revision:x"]}')),
    "rules_fuchsia 404 at integration revision":
        ("rules_fuchsia", lambda s: s.cipd.pop(("fuchsia/development/rules_fuchsia", f"git_revision:{INTEG}"))),
    "rules_fuchsia version tag names another instance":
        ("rules_fuchsia", lambda s: s.cipd.__setitem__(("fuchsia/development/rules_fuchsia", f"version:{V}"), "e" * 64)),
    "rules_fuchsia version lookup fails other than 404":
        ("rules_fuchsia", lambda s: s.cipd.__setitem__(("fuchsia/development/rules_fuchsia", f"version:{V}"), 500)),
}


@pytest.mark.parametrize("case", sorted(FAILURES))
def test_failure_names_field_and_leaves_lock_unchanged(case, tmp_path, capsys):
    field, breaker = FAILURES[case]
    out = tmp_path / "overlay.lock.json"
    out.write_bytes(b"previous lock\n")
    before = os.stat(out)
    stub = Stub()
    breaker(stub)
    assert run(stub, out) != 0
    err = capsys.readouterr().err
    assert f"error: {field}: " in err, err
    assert "left unchanged" in err
    assert out.read_bytes() == b"previous lock\n"
    assert os.stat(out).st_ino == before.st_ino
    assert sorted(p.name for p in tmp_path.iterdir()) == ["overlay.lock.json"]


def test_failure_without_existing_lock_creates_nothing(tmp_path):
    stub = Stub()
    stub.gets.pop(PB_URL)
    assert run(stub, tmp_path / "lock.json") != 0
    assert list(tmp_path.iterdir()) == []


@pytest.mark.parametrize("bad", ["", "latest", "33.x.1", "../33.1", "33.20260927.4.1/"])
def test_malformed_version_rejected_before_any_request(bad, tmp_path, capsys):
    stub = Stub()
    assert run(stub, tmp_path / "lock.json", version=bad) != 0
    assert "error: sdk_version: " in capsys.readouterr().err
    assert stub.calls == []


def test_rules_fuchsia_without_version_tag_is_accepted(tmp_path):
    stub = Stub()
    stub.cipd.pop(("fuchsia/development/rules_fuchsia", f"version:{V}"))
    out = tmp_path / "lock.json"
    assert run(stub, out) == 0
    assert json.loads(out.read_text())["rules_fuchsia"]["value"] == RULES_ID


# --- atomic write ------------------------------------------------------------------


def test_failure_between_temp_write_and_replace_keeps_old_lock(tmp_path, monkeypatch):
    out = tmp_path / "overlay.lock.json"
    out.write_bytes(b"previous lock\n")

    def boom(src, dst):
        assert Path(src).read_bytes().startswith(b"{")  # the temp file was fully written
        raise OSError("simulated crash before rename")

    monkeypatch.setattr(rp.os, "replace", boom)
    with pytest.raises(OSError, match="simulated"):
        run(Stub(), out)
    assert out.read_bytes() == b"previous lock\n"
    assert [p.name for p in tmp_path.iterdir()] == ["overlay.lock.json"]


def test_failure_while_writing_temp_keeps_old_lock(tmp_path, monkeypatch):
    out = tmp_path / "overlay.lock.json"
    out.write_bytes(b"previous lock\n")
    monkeypatch.setattr(rp.os, "fsync", lambda fd: (_ for _ in ()).throw(OSError("disk full")))
    with pytest.raises(OSError, match="disk full"):
        rp.write_atomically(out, b"new")
    assert out.read_bytes() == b"previous lock\n"
    assert [p.name for p in tmp_path.iterdir()] == ["overlay.lock.json"]


# --- the live git path, against a local repository (no network) -------------------


def _git(*args, cwd):
    return subprocess.run(["git", *args], cwd=cwd, check=True, capture_output=True).stdout.decode().strip()


@pytest.fixture
def local_repo(tmp_path):
    """A two-commit repository served over file://; returns (url, first commit)."""
    src = tmp_path / "src"
    (src / "manifests").mkdir(parents=True)
    _git("init", "-q", cwd=src)
    _git("config", "uploadpack.allowFilter", "true", cwd=src)
    _git("config", "uploadpack.allowAnySHA1InWant", "true", cwd=src)
    (src / "manifests" / "toolchain").write_bytes(b"old\n")
    _git("add", ".", cwd=src)
    commit = ["-c", "user.name=t", "-c", "user.email=t@example.invalid", "-c", "commit.gpgsign=false", "commit", "-q"]
    _git(*commit, "-m", "one", cwd=src)
    first = _git("rev-parse", "HEAD", cwd=src)
    (src / "manifests" / "toolchain").write_bytes(TOOLCHAIN_XML)
    _git(*commit, "-am", "two", cwd=src)
    return src.as_uri(), first


def test_live_git_show_reads_files_at_a_commit(local_repo):
    url, first = local_repo
    up = rp.LiveUpstream()
    try:
        assert up.git_show(url, first, "manifests/toolchain") == b"old\n"
        with pytest.raises(rp.FetchError, match="cat-file"):
            up.git_show(url, first, "no/such/file")
        with pytest.raises(rp.FetchError, match="fetch"):
            up.git_show(url, "0" * 40, "manifests/toolchain")
    finally:
        up.close()


def test_live_git_ignores_user_and_env_git_config(local_repo, tmp_path, monkeypatch):
    """C1: config from HOME, XDG, GIT_CONFIG_* and ~/.netrc must not reach the fetch.

    The hostile config rewrites the repository URL to a path that does not exist, sets a
    cookie file and an extra header, and a ~/.netrc holds a password. The control run
    shows plain git obeys it; the resolver's git must not.
    """
    url, first = local_repo
    home = tmp_path / "hostile-home"
    (home / "git").mkdir(parents=True)
    bogus = (tmp_path / "does-not-exist").as_uri()
    hostile = (f'[url "{bogus}"]\n\tinsteadOf = {url}\n'
               f"[http]\n\tcookiefile = {home}/cookies\n\textraHeader = Authorization: Bearer leaked\n")
    (home / ".gitconfig").write_text(hostile)
    (home / "git" / "config").write_text(hostile)
    (home / "cookies").write_text(".googlesource.com\tTRUE\t/\tTRUE\t2147483647\to\tgit-x=leaked\n")
    (home / ".netrc").write_text("machine fuchsia.googlesource.com login x password leaked\n")
    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setenv("XDG_CONFIG_HOME", str(home))
    monkeypatch.delenv("GIT_CONFIG_GLOBAL", raising=False)
    monkeypatch.delenv("GIT_CONFIG_NOSYSTEM", raising=False)
    monkeypatch.setenv("GIT_CONFIG_COUNT", "1")
    monkeypatch.setenv("GIT_CONFIG_KEY_0", f"url.{bogus}.insteadOf")
    monkeypatch.setenv("GIT_CONFIG_VALUE_0", url)
    monkeypatch.setenv("GIT_CONFIG_PARAMETERS", f"'url.{bogus}.insteadof'='{url}'")

    # Control: plain git under this environment is redirected and fails.
    probe = tmp_path / "probe.git"
    subprocess.run(["git", "init", "-q", "--bare", str(probe)], check=True, capture_output=True)
    control = subprocess.run(["git", "-C", str(probe), "fetch", "-q", "--depth", "1", url, first],
                             capture_output=True)
    assert control.returncode != 0 and b"does-not-exist" in control.stderr

    up = rp.LiveUpstream()
    try:
        assert up.git_show(url, first, "manifests/toolchain") == b"old\n"
    finally:
        up.close()


def _serve_once(handler_body):
    """Serve one HTTP response on 127.0.0.1 from a thread; returns the URL."""
    import http.server
    import threading

    class Handler(http.server.BaseHTTPRequestHandler):
        def do_GET(self):  # noqa: N802
            handler_body(self)

        def log_message(self, *args):
            pass

    server = http.server.HTTPServer(("127.0.0.1", 0), Handler)
    threading.Thread(target=server.handle_request, daemon=True).start()
    return f"http://127.0.0.1:{server.server_port}/core.tar.gz"


def _truncated(h):
    h.send_response(200)
    h.send_header("Content-Length", "1000")
    h.end_headers()
    h.wfile.write(b"only a little")
    h.wfile.flush()
    h.close_connection = True


def test_live_digest_truncated_body_is_a_fetch_error(monkeypatch):
    monkeypatch.setenv("no_proxy", "127.0.0.1")
    with pytest.raises(rp.FetchError, match="IncompleteRead"):
        rp.LiveUpstream().digest(_serve_once(_truncated))


def test_live_get_truncated_body_is_a_fetch_error(monkeypatch):
    monkeypatch.setenv("no_proxy", "127.0.0.1")
    with pytest.raises(rp.FetchError, match="IncompleteRead"):
        rp.LiveUpstream().get(_serve_once(_truncated))


def test_truncated_idk_stream_names_bazel_sdk(tmp_path, capsys):
    stub = Stub()
    live = rp.LiveUpstream()
    stub.digest = lambda url: live.digest(_serve_once(_truncated))
    out = tmp_path / "lock.json"
    assert run(stub, out) != 0
    assert "error: bazel_sdk: " in capsys.readouterr().err
    assert not out.exists()


# --- file mode -------------------------------------------------------------------------


def test_new_lock_is_world_readable(tmp_path):
    out = tmp_path / "lock.json"
    old = os.umask(0o022)
    try:
        assert run(Stub(), out) == 0
    finally:
        os.umask(old)
    assert os.stat(out).st_mode & 0o777 == 0o644


def test_rewritten_lock_keeps_existing_mode(tmp_path):
    out = tmp_path / "lock.json"
    out.write_bytes(b"old\n")
    os.chmod(out, 0o664)
    assert run(Stub(), out) == 0
    assert os.stat(out).st_mode & 0o777 == 0o664


def test_parse_toolchain_manifest_reads_both_pins():
    assert rp.parse_toolchain_manifest(TOOLCHAIN_XML) == {"rust_host": RUST_PIN, "rust_target": RUST_PIN}


def test_cipd_xssi_prefix_is_stripped():
    stub = Stub()
    assert rp.cipd_resolve(stub, "rust_host", "fuchsia/third_party/rust/host/linux-amd64", RUST_PIN) == HOST_ID
