# SPDX-FileCopyrightText: 2026 Curtis Galloway
# SPDX-License-Identifier: Apache-2.0
"""Tests for scripts/regen.py (the vendor stage, milestone M5), on a tiny fake fuchsia.git."""

from __future__ import annotations

import hashlib
import json
import subprocess
from pathlib import Path

import pytest

import regen

REV = "a" * 40

CARGO_LOCK = b'''\
version = 4

[[package]]
name = "foo"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "1111111111111111111111111111111111111111111111111111111111111111"
dependencies = ["bar"]

[[package]]
name = "bar"
version = "0.2.0-rc.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "2222222222222222222222222222222222222222222222222222222222222222"

[[package]]
name = "baz"
version = "0.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "3333333333333333333333333333333333333333333333333333333333333333"
'''

A_BUILD = '''\
# Copyright 2025 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//visibility:public"],
)

# A comment naming "//build/not/a/label" is left alone.
rustc_library(
    name = "a",
    srcs = ["src/lib.rs"],
    edition = "2024",
    lint_config = "//build/config/rust/lints:clippy_warn_all",
    deps = [
        "//sdk/rust/b",
        "//third_party/rust_crates/vendor:foo",
    ] + select({
        "//conditions:default": [],
    }),
)
'''

B_OVERLAY = '''\
# SPDX-FileCopyrightText: 2026 Curtis Galloway
# SPDX-License-Identifier: Apache-2.0

load("//rules:rustc.bzl", "rustc_library")

rustc_library(
    name = "b",
    srcs = ["src/lib.rs"],
    edition = "2024",
    vendored = True,
    visibility = ["//visibility:public"],
)
'''

ALIASES = '''\
package(default_visibility = ["//visibility:public"])

alias(
    name = "foo",
    actual = "//third_party/rust_crates/vendor/foo-1.0.0:foo",
    tags = ["manual"],
)

alias(
    name = "baz",
    actual = "//third_party/rust_crates/vendor/baz-0.1.0:baz",
    tags = ["manual"],
)
'''


def _crate_build(name, version, deps=()):
    dep_lines = "".join(f'        "{d}",\n' for d in deps)
    return f'''\
# @generated by crate_universe
load("@rules_rust//rust:defs.bzl", "rust_library")

package(default_visibility = ["//visibility:public"])

package_info(
    name = "package_info",
    package_name = "{name}",
    package_url = "https://example.invalid/{name}",
    package_version = "{version}",
)

rust_library(
    name = "{name}",
    srcs = glob(["**/*.rs"]),
    target_compatible_with = select({{
        "@rules_rust//rust/platform:x86_64-unknown-fuchsia": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }}),
    deps = [
{dep_lines}    ],
)
'''


def _write(root: Path, rel: str, data, mode=0o644):
    p = root / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_bytes(data if isinstance(data, bytes) else data.encode())
    p.chmod(mode)


def make_upstream(root: Path) -> Path:
    _write(root, "LICENSE", "Fuchsia license text\n")
    _write(root, "PATENTS", "Fuchsia patents text\n")
    _write(root, "sdk/rust/a/BUILD.bazel", A_BUILD)
    _write(root, "sdk/rust/a/BUILD.gn", "# gn\n")
    _write(root, "sdk/rust/a/src/lib.rs", "pub fn a() -> u32 {\n    1\n}\n")
    _write(root, "sdk/rust/a/tool.sh", "#!/bin/sh\n", 0o755)
    # A package of its own inside the crate directory: not copied with it.
    _write(root, "sdk/rust/a/nested/BUILD.gn", "# gn\n")
    _write(root, "sdk/rust/a/nested/src/lib.rs", "// nested\n")
    _write(root, "sdk/rust/b/BUILD.gn", "# gn only\n")
    _write(root, "sdk/rust/b/src/lib.rs", "pub fn b() {}\n")
    _write(root, "third_party/rust_crates/Cargo.lock", CARGO_LOCK)
    _write(root, "third_party/rust_crates/vendor/BUILD.bazel", ALIASES)
    _write(root, "third_party/rust_crates/vendor/foo-1.0.0/BUILD.bazel", _crate_build(
        "foo", "1.0.0", ["//third_party/rust_crates/vendor/bar-0.2.0-rc.1:bar"]))
    _write(root, "third_party/rust_crates/vendor/bar-0.2.0-rc.1/BUILD.bazel", _crate_build("bar", "0.2.0-rc.1"))
    _write(root, "third_party/rust_crates/vendor/baz-0.1.0/BUILD.bazel", _crate_build("baz", "0.1.0"))
    return root


def make_repo(root: Path, upstream: Path) -> Path:
    lock_sha = hashlib.sha256((upstream / "third_party/rust_crates/Cargo.lock").read_bytes()).hexdigest()
    lock = {"fuchsia_revision": {"value": REV, "source": []},
            "cargo_lock_sha256": {"value": lock_sha, "source": []}}
    _write(root, "overlay.lock.json", json.dumps(lock))
    _write(root, "vendor/crates.txt", "# comment\nsdk/rust/a upstream\nsdk/rust/b overlay  # ours\n")
    _write(root, "overlays/sdk/rust/b/BUILD.bazel", B_OVERLAY)
    return root


@pytest.fixture
def env(tmp_path):
    upstream = make_upstream(tmp_path / "fx")
    repo = make_repo(tmp_path / "repo", upstream)

    def run(*argv):
        return regen.main(list(argv), root=repo, make_source=lambda rev: regen.DirSource(upstream, rev))

    return upstream, repo, run


def _snapshot(root: Path) -> dict[str, tuple[bytes, int]]:
    out = {}
    for rel in regen.OUTPUTS:
        for p in sorted((root / rel).rglob("*")):
            if p.is_file():
                out[p.relative_to(root).as_posix()] = (p.read_bytes(), p.stat().st_mode & 0o777)
    return out


# --- label rewriting ---------------------------------------------------------------


def test_rewrite_maps_every_label_kind():
    out = regen.rewrite_upstream_build(A_BUILD, "sdk/rust/a/BUILD.bazel", {"sdk/rust/a", "sdk/rust/b"})
    assert 'load("//rules:rustc.bzl", "rustc_library")' in out
    assert '"//vendor/fuchsia:license"' in out
    assert '"//rules/lints:clippy_warn_all"' in out
    assert '"//vendor/fuchsia/sdk/rust/b"' in out
    assert '"@rust_crates//vendor:foo"' in out
    assert '"//visibility:public"' in out and '"//conditions:default"' in out
    assert '# A comment naming "//build/not/a/label" is left alone.' in out
    assert "rustc_library(\n    vendored = True,  # Generated by scripts/regen.py\n    name = \"a\"," in out
    # Nothing else changed: undoing the known edits gives the original back.
    undo = (out.replace("//rules:rustc.bzl", "//build/bazel/rules/rust:defs.bzl")
            .replace("//vendor/fuchsia:license", "//:license")
            .replace("//rules/lints:", "//build/config/rust/lints:")
            .replace("//vendor/fuchsia/sdk/rust/b", "//sdk/rust/b")
            .replace("@rust_crates//vendor:", "//third_party/rust_crates/vendor:")
            .replace("\n    vendored = True,  # Generated by scripts/regen.py", ""))
    assert undo == A_BUILD


def test_rewrite_target_in_vendored_package():
    text = 'x = ["//sdk/rust/b:b", "//sdk/rust/b:other"]\n'
    assert regen.rewrite_upstream_build(text, "f", {"sdk/rust/b"}) == \
        'x = ["//vendor/fuchsia/sdk/rust/b:b", "//vendor/fuchsia/sdk/rust/b:other"]\n'


@pytest.mark.parametrize("label, message", [
    ("//sdk/rust/missing", "sdk/rust/missing is not listed in vendor/crates.txt"),
    ("//third_party/rust_crates/forks/libc-0.2.189:libc", "patched and forked crates come in milestone M6"),
    ("//third_party/rust_crates/ask2patch/memchr", "patched and forked crates come in milestone M6"),
    ("//build/bazel/rules/other:defs.bzl", "no overlay mapping for this build label"),
])
def test_rewrite_fails_naming_file_and_label(label, message):
    with pytest.raises(regen.RegenError) as e:
        regen.rewrite_upstream_build(f'deps = ["{label}"]\n', "sdk/rust/a/BUILD.bazel", {"sdk/rust/a"})
    assert "sdk/rust/a/BUILD.bazel" in str(e.value) and label in str(e.value) and message in str(e.value)


def test_rewrite_rejects_rules_rustc_does_not_provide():
    text = 'load("//build/bazel/rules/rust:defs.bzl", "rustc_library", "rustc_test")\n'
    with pytest.raises(regen.RegenError, match="loads rustc_test from //rules:rustc.bzl"):
        regen.rewrite_upstream_build(text, "f", set())


def test_vendored_added_to_every_rustc_macro():
    text = ('rustc_library(\n    name = "l",\n)\n\nrustc_binary(name = "b")\n\n'
            '    rustc_proc_macro(\n        name = "p",\n        srcs = [f("(")],\n    )\n'
            '# rustc_library( in a comment\nx = "rustc_binary(" \n')
    out = regen.add_vendored(text, "f")
    assert out.count("vendored = True") == 3
    assert 'rustc_binary(vendored = True, name = "b")' in out
    assert "    rustc_proc_macro(\n        vendored = True,  # Generated by scripts/regen.py\n        name" in out
    assert "# rustc_library( in a comment" in out and 'x = "rustc_binary(" ' in out


def test_vendored_already_set_is_an_error():
    with pytest.raises(regen.RegenError, match="already sets vendored; regen.py adds it, so write an overlay"):
        regen.add_vendored('rustc_library(\n    name = "l",\n    vendored = False,\n)\n', "f")


def test_overlay_without_vendored_is_an_error():
    regen.check_overlay_build(B_OVERLAY, "o")
    with pytest.raises(regen.RegenError, match="o: rustc_library call without vendored = True"):
        regen.check_overlay_build(B_OVERLAY.replace("    vendored = True,\n", ""), "o")


def test_crate_build_rewrite_and_closure():
    text, deps = regen.rewrite_crate_build(
        _crate_build("foo", "1.0.0", ["//third_party/rust_crates/vendor/bar-0.2.0-rc.1:bar"]), "f")
    assert deps == {"bar-0.2.0-rc.1"}
    assert '"//vendor/bar-0.2.0-rc.1:bar"' in text
    assert '"@rules_rust//rust/platform:x86_64-unknown-fuchsia"' in text
    with pytest.raises(regen.RegenError, match="milestone M6"):
        regen.rewrite_crate_build('deps = ["//third_party/rust_crates/ask2patch/memchr"]', "f")


def test_vendor_list_parsing_errors():
    assert regen.read_vendor_list("a/b upstream\n\n# x\nc overlay # y\n") == [
        regen.Crate("a/b", "upstream"), regen.Crate("c", "overlay")]
    for bad, msg in [("a/b", "expected"), ("a/b copy", "expected"), ("/a upstream", "normalized"),
                     ("a/../b upstream", "normalized"), ("a/ upstream", "normalized"),
                     ("a upstream\na overlay", "listed twice")]:
        with pytest.raises(regen.RegenError, match=msg):
            regen.read_vendor_list(bad)


# --- end to end on the fake tree -------------------------------------------------------


def test_vendor_writes_the_expected_trees(env):
    upstream, repo, run = env
    assert run("vendor") == 0
    v = repo / "vendor/fuchsia"
    assert sorted(p.relative_to(v).as_posix() for p in v.rglob("*") if p.is_file()) == [
        "BUILD.bazel", "LICENSE", "PATENTS",
        "sdk/rust/a/BUILD.bazel", "sdk/rust/a/BUILD.gn", "sdk/rust/a/src/lib.rs", "sdk/rust/a/tool.sh",
        "sdk/rust/b/BUILD.bazel", "sdk/rust/b/BUILD.gn", "sdk/rust/b/src/lib.rs",
    ]
    # Copied byte for byte, modes kept; LICENSE covers the tree (C4).
    for rel in ("LICENSE", "PATENTS", "sdk/rust/a/src/lib.rs", "sdk/rust/b/src/lib.rs"):
        assert (v / rel).read_bytes() == (upstream / rel).read_bytes()
    assert (v / "sdk/rust/a/tool.sh").stat().st_mode & 0o111
    assert not (v / "sdk/rust/a/src/lib.rs").stat().st_mode & 0o111
    a = (v / "sdk/rust/a/BUILD.bazel").read_text()
    assert a.startswith(f"# Generated by scripts/regen.py from fuchsia.git {REV}:sdk/rust/a/BUILD.bazel\n")
    assert A_BUILD.splitlines()[0] in a  # upstream's own header is kept
    assert (v / "sdk/rust/b/BUILD.bazel").read_text() == B_OVERLAY
    assert 'license_text = "LICENSE"' in (v / "BUILD.bazel").read_text()

    c = repo / "third_party/crates"
    spec = json.loads((c / "crates.json").read_text())
    assert spec["aliases"] == ["foo"]  # baz is not used, so not fetched
    assert [(e["name"], e["version"], e["sha256"][:4], e["url"]) for e in spec["crates"]] == [
        ("bar", "0.2.0-rc.1", "2222", "https://static.crates.io/crates/bar/bar-0.2.0-rc.1.crate"),
        ("foo", "1.0.0", "1111", "https://static.crates.io/crates/foo/foo-1.0.0.crate"),
    ]
    assert spec["cargo_lock"].endswith(f"{REV}:third_party/rust_crates/Cargo.lock")
    assert '"//vendor/bar-0.2.0-rc.1:bar"' in (c / "BUILD.foo-1.0.0.bazel").read_text()
    aliases = (c / "BUILD.vendor.bazel").read_text()
    assert 'name = "foo",\n    actual = "//vendor/foo-1.0.0:foo"' in aliases and '"baz"' not in aliases
    assert sorted(p.name for p in c.iterdir()) == [
        "BUILD.bar-0.2.0-rc.1.bazel", "BUILD.bazel", "BUILD.foo-1.0.0.bazel", "BUILD.vendor.bazel", "crates.json"]


def test_vendor_is_reproducible_and_removes_stale_files(env):
    _, repo, run = env
    assert run("vendor") == 0
    first = _snapshot(repo)
    _write(repo, "vendor/fuchsia/sdk/rust/a/stale.rs", "old\n")
    assert run("vendor") == 0
    assert _snapshot(repo) == first
    assert not any(p.name.endswith((".regen-new", ".regen-old")) for p in (repo / "vendor").iterdir())


def test_check_passes_on_a_clean_tree(env, capsys):
    _, repo, run = env
    assert run("vendor") == 0
    assert run("--check") == 0
    assert "match fuchsia.git" in capsys.readouterr().out


def test_check_names_a_one_byte_hand_edit(env, capsys):
    _, repo, run = env
    assert run("vendor") == 0
    f = repo / "vendor/fuchsia/sdk/rust/a/src/lib.rs"
    data = bytearray(f.read_bytes())
    data[-3] ^= 1  # "1" -> "0": one byte
    f.write_bytes(bytes(data))
    capsys.readouterr()
    assert run("--check") == 1
    err = capsys.readouterr().err
    assert "vendor/fuchsia/sdk/rust/a/src/lib.rs: content differs" in err
    assert "1 file(s) drift" in err


@pytest.mark.parametrize("change, expected", [
    (lambda r: (r / "vendor/fuchsia/sdk/rust/a/extra.rs").write_text("x"),
     "vendor/fuchsia/sdk/rust/a/extra.rs: not generated by regen.py"),
    (lambda r: (r / "vendor/fuchsia/PATENTS").unlink(), "vendor/fuchsia/PATENTS: missing"),
    (lambda r: (r / "vendor/fuchsia/sdk/rust/a/tool.sh").chmod(0o644),
     "vendor/fuchsia/sdk/rust/a/tool.sh: executable bit differs"),
    (lambda r: (r / "third_party/crates/crates.json").write_text("{}\n"),
     "third_party/crates/crates.json: content differs"),
])
def test_check_detects_other_drift(env, capsys, change, expected):
    _, repo, run = env
    assert run("vendor") == 0
    change(repo)
    capsys.readouterr()
    assert run("--check") == 1
    assert expected in capsys.readouterr().err


def test_check_detects_an_input_change(env, capsys):
    """Changing an overlay without rerunning vendor is drift too."""
    _, repo, run = env
    assert run("vendor") == 0
    ov = repo / "overlays/sdk/rust/b/BUILD.bazel"
    ov.write_text(ov.read_text() + "# changed\n")
    assert run("--check") == 1
    assert "vendor/fuchsia/sdk/rust/b/BUILD.bazel: content differs" in capsys.readouterr().err


def _patch(old: str, new: str, path="sdk/rust/a/src/lib.rs") -> str:
    return (f"--- a/{path}\n+++ b/{path}\n@@ -1,3 +1,3 @@\n pub fn a() -> u32 {{\n"
            f"-    {old}\n+    {new}\n }}\n")


def test_patches_apply_in_name_order(env):
    _, repo, run = env
    _write(repo, "patches/fuchsia/sdk/rust/a/0001-two.patch", _patch("1", "2"))
    _write(repo, "patches/fuchsia/sdk/rust/a/0002-three.patch", _patch("2", "3"))
    assert run("vendor") == 0
    assert (repo / "vendor/fuchsia/sdk/rust/a/src/lib.rs").read_text() == "pub fn a() -> u32 {\n    3\n}\n"
    assert run("--check") == 0


def test_a_patch_that_does_not_apply_names_patch_and_file(env, capsys):
    _, repo, run = env
    assert run("vendor") == 0
    before = _snapshot(repo)
    _write(repo, "patches/fuchsia/sdk/rust/a/0001-stale.patch", _patch("7", "8"))
    assert run("vendor") == 2
    err = capsys.readouterr().err
    assert "patches/fuchsia/sdk/rust/a/0001-stale.patch: does not apply to " \
           "vendor/fuchsia/sdk/rust/a/src/lib.rs" in err
    assert _snapshot(repo) == before  # nothing replaced


def test_a_patch_for_a_missing_file_names_it(env, capsys):
    _, repo, run = env
    _write(repo, "patches/fuchsia/sdk/rust/a/0001-gone.patch", _patch("1", "2", "sdk/rust/a/src/gone.rs"))
    assert run("vendor") == 2
    assert "0001-gone.patch: does not apply to vendor/fuchsia/sdk/rust/a/src/gone.rs" in capsys.readouterr().err


def test_a_patch_may_touch_only_its_own_crate(env, capsys):
    _, repo, run = env
    _write(repo, "patches/fuchsia/sdk/rust/b/0001-wrong-place.patch", _patch("1", "2"))
    assert run("vendor") == 2
    assert ("patches/fuchsia/sdk/rust/b/0001-wrong-place.patch: patches under patches/fuchsia/sdk/rust/b/ "
            "may change only files of sdk/rust/b; this one changes sdk/rust/a/src/lib.rs") in capsys.readouterr().err


@pytest.mark.parametrize("edit, message", [
    (lambda up, repo: (repo / "vendor/crates.txt").write_text("sdk/rust/a upstream\n"),
     "sdk/rust/b is not listed in vendor/crates.txt"),
    (lambda up, repo: ((repo / "vendor/crates.txt").write_text("sdk/rust/a upstream\nsdk/rust/b upstream\n"),
                       (repo / "overlays/sdk/rust/b/BUILD.bazel").unlink()),
     "sdk/rust/b is 'upstream', but upstream has no BUILD.bazel"),
    (lambda up, repo: (repo / "vendor/crates.txt").write_text("sdk/rust/a upstream\nsdk/rust/b upstream\n"),
     "overlays/sdk/rust/b/BUILD.bazel exists, but vendor/crates.txt says 'upstream'"),
    (lambda up, repo: (repo / "overlays/sdk/rust/b/BUILD.bazel").unlink(),
     "overlays/sdk/rust/b/BUILD.bazel does not exist"),
    (lambda up, repo: _write(repo, "overlays/sdk/rust/a/BUILD.bazel", B_OVERLAY),
     "overlays/sdk/rust/a/BUILD.bazel exists, but vendor/crates.txt says 'upstream'"),
    (lambda up, repo: _write(up, "third_party/rust_crates/Cargo.lock", CARGO_LOCK + b"\n"),
     "third_party/rust_crates/Cargo.lock: SHA-256"),
    (lambda up, repo: _write(up, "third_party/rust_crates/Cargo.lock", CARGO_LOCK.replace(b'"bar"', b'"bar2"'))
     or make_repo(repo, up),
     "bar 0.2.0-rc.1 is not a crates.io package"),
    (lambda up, repo: _write(up, "third_party/rust_crates/vendor/BUILD.bazel", ALIASES.replace('"foo"', '"foo2"')),
     "has no alias 'foo'"),
    (lambda up, repo: (repo / "vendor/crates.txt").write_text("sdk/rust/a upstream\nsdk/rust/b overlay\nsdk/x upstream\n"),
     "sdk/x: no such directory"),
    (lambda up, repo: _write(repo, "overlays/sdk/rust/c/BUILD.bazel", B_OVERLAY),
     "overlays/sdk/rust/c/BUILD.bazel: sdk/rust/c is not listed in vendor/crates.txt"),
    (lambda up, repo: _write(repo, "patches/fuchsia/sdk/rust/c/0001-x.patch", _patch("1", "2")),
     "patches/fuchsia/sdk/rust/c/0001-x.patch: sdk/rust/c is not listed in vendor/crates.txt"),
])
def test_input_errors_name_the_input(env, capsys, edit, message):
    upstream, repo, run = env
    edit(upstream, repo)
    assert run("vendor") == 2
    assert message in capsys.readouterr().err
    assert not (repo / "vendor/fuchsia").exists()


def test_needs_a_stage_or_check(env):
    _, _, run = env
    with pytest.raises(SystemExit):
        run()


# --- the git source, against a local repository (no network) -------------------------


def _git(*args, cwd):
    return subprocess.run(["git", *args], cwd=cwd, check=True, capture_output=True).stdout.decode().strip()


@pytest.fixture
def git_upstream(tmp_path):
    src = make_upstream(tmp_path / "src")
    _git("init", "-q", cwd=src)
    _git("config", "uploadpack.allowFilter", "true", cwd=src)
    _git("config", "uploadpack.allowAnySHA1InWant", "true", cwd=src)
    _git("add", ".", cwd=src)
    _git("-c", "user.name=t", "-c", "user.email=t@example.invalid", "-c", "commit.gpgsign=false",
         "commit", "-q", "-m", "one", cwd=src)
    return src, _git("rev-parse", "HEAD", cwd=src)


def test_git_source_reads_files_and_modes(git_upstream, tmp_path):
    src, rev = git_upstream
    s = regen.GitSource(src.as_uri(), rev, tmp_path / "work")
    files = s.files("sdk/rust/a")
    assert files["sdk/rust/a/tool.sh"] == 0o755 and files["sdk/rust/a/src/lib.rs"] == 0o644
    assert "sdk/rust/a/nested/src/lib.rs" in files
    got = s.read(["LICENSE", "sdk/rust/a/src/lib.rs", "LICENSE"])
    assert got["sdk/rust/a/src/lib.rs"] == (src / "sdk/rust/a/src/lib.rs").read_bytes()
    assert got["LICENSE"] == b"Fuchsia license text\n"
    with pytest.raises(regen.RegenError, match="no such directory"):
        s.files("sdk/rust/nope")
    with pytest.raises(regen.RegenError, match="no such file"):
        s.read(["sdk/rust/nope.rs"])
    # "sdk/rust/a" must not match "sdk/rust/ab".
    assert all(f.startswith("sdk/rust/a/") for f in files)


def test_git_source_unknown_revision_fails(git_upstream, tmp_path):
    src, _ = git_upstream
    with pytest.raises(regen.RegenError, match="fetch"):
        regen.GitSource(src.as_uri(), "0" * 40, tmp_path / "work")


def test_vendor_from_git_matches_vendor_from_directory(git_upstream, tmp_path):
    src, rev = git_upstream
    repo_git = make_repo(tmp_path / "r1", src)
    repo_dir = make_repo(tmp_path / "r2", src)
    for repo in (repo_git, repo_dir):
        lock = json.loads((repo / "overlay.lock.json").read_text())
        lock["fuchsia_revision"]["value"] = rev
        (repo / "overlay.lock.json").write_text(json.dumps(lock))
    assert regen.main(["vendor"], root=repo_git,
                      make_source=lambda r: regen.GitSource(src.as_uri(), r, tmp_path / "w")) == 0
    assert regen.main(["vendor"], root=repo_dir, make_source=lambda r: regen.DirSource(src, r)) == 0
    snap = {k: v for k, v in _snapshot(repo_git).items()}
    assert snap == _snapshot(repo_dir) and snap
