# SPDX-FileCopyrightText: 2026 Curtis Galloway
# SPDX-License-Identifier: Apache-2.0
"""Tests for scripts/regen.py (the vendor stage, milestone M5), on a tiny fake fuchsia.git."""

from __future__ import annotations

import difflib
import hashlib
import json
import subprocess
from pathlib import Path

import pytest

import regen

REV = "a" * 40
ROOT = Path(__file__).resolve().parent.parent

CARGO_LOCK = b'''\
version = 4

[[package]]
name = "foo"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "1111111111111111111111111111111111111111111111111111111111111111"
dependencies = ["bar"]

[[package]]
name = "bar"
version = "0.2.0-rc.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "2222222222222222222222222222222222222222222222222222222222222222"

[[package]]
name = "baz"
version = "0.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "3333333333333333333333333333333333333333333333333333333333333333"

[[package]]
name = "memo"
version = "2.0.0"

[[package]]
name = "qux"
version = "0.3.0"
'''

A_BUILD = '''\
# Copyright 2025 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//visibility:public"],
)

# A comment naming "//build/not/a/label" is left alone.
rustc_library(
    name = "a",
    srcs = ["src/lib.rs"],
    edition = "2024",
    lint_config = "//build/config/rust/lints:clippy_warn_all",
    deps = [
        "//sdk/rust/b",
        "//third_party/rust_crates/vendor:foo",
    ] + select({
        "//conditions:default": [],
    }),
)
'''

B_OVERLAY = '''\
# SPDX-FileCopyrightText: 2026 Curtis Galloway
# SPDX-License-Identifier: Apache-2.0

load("//rules:rustc.bzl", "rustc_library")

rustc_library(
    name = "b",
    srcs = ["src/lib.rs"],
    edition = "2024",
    vendored = True,
    visibility = ["//visibility:public"],
)
'''

ALIASES = '''\
package(default_visibility = ["//visibility:public"])

alias(
    name = "foo",
    actual = "//third_party/rust_crates/vendor/foo-1.0.0:foo",
    tags = ["manual"],
)

alias(
    name = "baz",
    actual = "//third_party/rust_crates/vendor/baz-0.1.0:baz",
    tags = ["manual"],
)

alias(
    name = "qux",
    actual = "//third_party/rust_crates/forks/qux-0.3.0:qux",
    tags = ["manual"],
)
'''


def _crate_build(name, version, deps=()):
    dep_lines = "".join(f'        "{d}",\n' for d in deps)
    return f'''\
# @generated by crate_universe
load("@rules_rust//rust:defs.bzl", "rust_library")

package(default_visibility = ["//visibility:public"])

package_info(
    name = "package_info",
    package_name = "{name}",
    package_url = "https://example.invalid/{name}",
    package_version = "{version}",
)

rust_library(
    name = "{name}",
    srcs = glob(["**/*.rs"]),
    target_compatible_with = select({{
        "@rules_rust//rust/platform:x86_64-unknown-fuchsia": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }}),
    deps = [
{dep_lines}    ],
)
'''


def _write(root: Path, rel: str, data, mode=0o644):
    p = root / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_bytes(data if isinstance(data, bytes) else data.encode())
    p.chmod(mode)


def make_upstream(root: Path) -> Path:
    _write(root, "LICENSE", "Fuchsia license text\n")
    _write(root, "PATENTS", "Fuchsia patents text\n")
    _write(root, "rustfmt.toml", 'edition = "2024"\n')
    _write(root, "sdk/rust/a/BUILD.bazel", A_BUILD)
    _write(root, "sdk/rust/a/BUILD.gn", "# gn\n")
    _write(root, "sdk/rust/a/src/lib.rs", "pub fn a() -> u32 {\n    1\n}\n")
    _write(root, "sdk/rust/a/tool.sh", "#!/bin/sh\n", 0o755)
    # A package of its own inside the crate directory: not copied with it.
    _write(root, "sdk/rust/a/nested/BUILD.gn", "# gn\n")
    _write(root, "sdk/rust/a/nested/src/lib.rs", "// nested\n")
    _write(root, "sdk/rust/b/BUILD.gn", "# gn only\n")
    _write(root, "sdk/rust/b/src/lib.rs", "pub fn b() {}\n")
    _write(root, "third_party/rust_crates/Cargo.lock", CARGO_LOCK)
    _write(root, "third_party/rust_crates/vendor/BUILD.bazel", ALIASES)
    _write(root, "third_party/rust_crates/vendor/foo-1.0.0/BUILD.bazel", _crate_build(
        "foo", "1.0.0", ["//third_party/rust_crates/vendor/bar-0.2.0-rc.1:bar"]))
    _write(root, "third_party/rust_crates/vendor/bar-0.2.0-rc.1/BUILD.bazel", _crate_build(
        "bar", "0.2.0-rc.1", ["//third_party/rust_crates/ask2patch/memo:memo"]))
    # Patched crates (M6b): sources only in fuchsia.git, copied with their license files.
    _write(root, "third_party/rust_crates/ask2patch/memo/BUILD.bazel", _crate_build("memo", "2.0.0"))
    _write(root, "third_party/rust_crates/ask2patch/memo/LICENSE-MIT", "MIT text\n")
    _write(root, "third_party/rust_crates/ask2patch/memo/src/lib.rs", "pub fn memo() {}\n")
    _write(root, "third_party/rust_crates/ask2patch/memo/gen.sh", "#!/bin/sh\n", 0o755)
    _write(root, "third_party/rust_crates/forks/qux-0.3.0/BUILD.bazel", _crate_build(
        "qux", "0.3.0", ["//third_party/rust_crates/forks/qux-0.3.0:build_script_build",
                         "//third_party/rust_crates/vendor/baz-0.1.0:baz"]))
    _write(root, "third_party/rust_crates/forks/qux-0.3.0/src/lib.rs", "pub fn qux() {}\n")
    _write(root, "third_party/rust_crates/vendor/baz-0.1.0/BUILD.bazel", _crate_build("baz", "0.1.0"))
    return root


def make_repo(root: Path, upstream: Path) -> Path:
    lock_sha = hashlib.sha256((upstream / "third_party/rust_crates/Cargo.lock").read_bytes()).hexdigest()
    lock = {"fuchsia_revision": {"value": REV, "source": []},
            "cargo_lock_sha256": {"value": lock_sha, "source": []}}
    _write(root, "overlay.lock.json", json.dumps(lock))
    _write(root, "vendor/crates.txt", "# comment\nsdk/rust/a upstream\nsdk/rust/b overlay  # ours\n")
    _write(root, "vendor/crates_io.txt", "# none yet\n")
    _write(root, "overlays/sdk/rust/b/BUILD.bazel", B_OVERLAY)
    return root


@pytest.fixture
def env(tmp_path):
    upstream = make_upstream(tmp_path / "fx")
    repo = make_repo(tmp_path / "repo", upstream)

    def run(*argv):
        return regen.main(list(argv), root=repo, make_source=lambda rev: regen.DirSource(upstream, rev))

    return upstream, repo, run


def _snapshot(root: Path) -> dict[str, tuple[bytes, int]]:
    out = {}
    for rel in regen.OUTPUTS:
        for p in sorted((root / rel).rglob("*")):
            if p.is_file():
                out[p.relative_to(root).as_posix()] = (p.read_bytes(), p.stat().st_mode & 0o777)
    return out


# --- label rewriting ---------------------------------------------------------------

_HDR = ("# Copyright 2025 The Fuchsia Authors. All rights reserved.\n"
        "# Use of this source code is governed by a BSD-style license that can be\n"
        "# found in the LICENSE file.\n\n")

# Real upstream files at b5274053cc0f (the review's cases).
FUCHSIA_ASYNC_MACRO = _HDR + '''\
load("@rules_rust//rust:defs.bzl", "rust_proc_macro")

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//visibility:public"],
)

rust_proc_macro(
    name = "fuchsia-async-macro",
    srcs = ["src/lib.rs"],
    edition = "2024",
    version = "0.1.0",
    deps = [
        "//third_party/rust_crates/vendor:proc-macro2",
        "//third_party/rust_crates/vendor:quote",
        "//third_party/rust_crates/vendor:syn",
    ],
)
'''

FROM_ENUM = _HDR + '''\
load(
    "//build/bazel/rules/rust:defs.bzl",
    "rustc_library",
    "rustc_proc_macro",
)

package(default_applicable_licenses = ["//:license"])

rustc_library(
    name = "from-enum",
    srcs = [
        "src/lib.rs",
    ],
    crate_name = "from_enum",
    edition = "2024",
    proc_macro_deps = [":from-enum-derive"],
    visibility = ["//:__subpackages__"],
)

rustc_proc_macro(
    name = "from-enum-derive",
    srcs = ["src/macro.rs"],
    crate_root = "src/macro.rs",
    edition = "2024",
    deps = [
        "//third_party/rust_crates/vendor:darling",
        "//third_party/rust_crates/vendor:proc-macro2",
        "//third_party/rust_crates/vendor:quote",
        "//third_party/rust_crates/vendor:syn",
    ],
)
'''

_MARK = "\n    vendored = True,  # Generated by scripts/regen.py"


def test_rewrite_maps_every_label_kind():
    out = regen.rewrite_upstream_build(A_BUILD, "sdk/rust/a/BUILD.bazel", {"sdk/rust/a", "sdk/rust/b"})
    assert 'load("//rules:rustc.bzl", "rustc_library")' in out
    assert '"//vendor/fuchsia:license"' in out
    assert '"//rules/lints:clippy_warn_all"' in out
    assert '"//vendor/fuchsia/sdk/rust/b"' in out
    assert '"@rust_crates//vendor:foo"' in out
    assert '"//visibility:public"' in out and '"//conditions:default"' in out
    assert '# A comment naming "//build/not/a/label" is left alone.' in out
    assert "rustc_library(" + _MARK + "\n    name = \"a\"," in out
    # Nothing else changed: undoing the known edits gives the original back.
    undo = (out.replace("//rules:rustc.bzl", "//build/bazel/rules/rust:defs.bzl")
            .replace("//vendor/fuchsia:license", "//:license")
            .replace("//rules/lints:", "//build/config/rust/lints:")
            .replace("//vendor/fuchsia/sdk/rust/b", "//sdk/rust/b")
            .replace("@rust_crates//vendor:", "//third_party/rust_crates/vendor:")
            .replace(_MARK, ""))
    assert undo == A_BUILD


def test_rewrite_maps_patched_crates_into_rust_crates():
    """M6b: an in-tree label straight into a patched crate goes to its @rust_crates package."""
    text = 'x = ["//third_party/rust_crates/forks/libc-0.2.189:libc", "//third_party/rust_crates/ask2patch/memchr"]\n'
    assert regen.rewrite_upstream_build(text, "f", set()) == \
        'x = ["@rust_crates//forks/libc-0.2.189:libc", "@rust_crates//ask2patch/memchr"]\n'


@pytest.mark.parametrize("pkg, expected", [
    ("third_party/rust_crates/vendor/foo-1.0.0", "vendor/foo-1.0.0"),
    ("third_party/rust_crates/forks/libc-0.2.189", "forks/libc-0.2.189"),
    ("third_party/rust_crates/forks/bluetooth/bt-bass", "forks/bluetooth/bt-bass"),
    ("third_party/rust_crates/ask2patch/memchr", "ask2patch/memchr"),
    ("third_party/rust_crates/vendor", None),
    ("third_party/rust_crates/vendor/a/b", None),
    ("third_party/rust_crates/forks", None),
    ("third_party/rust_crates/other/x", None),
    ("third_party/rust_crates", None),
    ("sdk/rust/zx", None),
])
def test_crate_dir(pkg, expected):
    assert regen.crate_dir(pkg) == expected


def test_rewrite_target_in_vendored_package():
    text = 'x = ["//sdk/rust/b:b", "//sdk/rust/b:other"]\n'
    assert regen.rewrite_upstream_build(text, "f", {"sdk/rust/b"}) == \
        'x = ["//vendor/fuchsia/sdk/rust/b:b", "//vendor/fuchsia/sdk/rust/b:other"]\n'


def test_rules_rust_rules_are_mapped_to_the_wrappers():
    """src/lib/fuchsia-async-macro calls rust_proc_macro from @rules_rust directly."""
    out = regen.rewrite_upstream_build(FUCHSIA_ASYNC_MACRO, "src/lib/fuchsia-async-macro/BUILD.bazel", set())
    assert 'load("//rules:rustc.bzl", rust_proc_macro = "rustc_proc_macro")' in out
    assert "rust_proc_macro(" + _MARK + '\n    name = "fuchsia-async-macro",' in out
    assert '"@rust_crates//vendor:syn"' in out and "@rules_rust" not in out


def test_root_visibility_and_multiline_load():
    """src/lib/from-enum: a multi-line load and visibility = ["//:__subpackages__"]."""
    out = regen.rewrite_upstream_build(FROM_ENUM, "src/lib/from-enum/BUILD.bazel", {"src/lib/from-enum"})
    assert '"//vendor/fuchsia:__subpackages__"' in out
    assert 'load(\n    "//rules:rustc.bzl",\n    "rustc_library",\n    "rustc_proc_macro",\n)' in out
    assert out.count("vendored = True") == 2


def test_visibility_may_name_packages_that_are_not_vendored():
    text = 'x = ["//src/other:__pkg__", "//src/other:__subpackages__"]\n'
    assert regen.rewrite_upstream_build(text, "f", set()) == \
        'x = ["//vendor/fuchsia/src/other:__pkg__", "//vendor/fuchsia/src/other:__subpackages__"]\n'


@pytest.mark.parametrize("label, message", [
    ("//sdk/rust/missing", "sdk/rust/missing is not listed in vendor/crates.txt"),
    ("//third_party/rust_crates:Cargo.toml", "only crates.io crates (third_party/rust_crates/vendor) and patched"),
    ("//third_party/rust_crates/vendor/foo-1.0.0:foo", "use an alias from third_party/rust_crates/vendor"),
    ("//third_party/rust_crates/other/x", "only crates.io crates"),
    ("//third_party/rust_crates/forks", "only crates.io crates"),
    ("//build/bazel/rules/other:thing", "no overlay mapping for this label"),
    ("//:something", "no overlay mapping for this label"),
])
def test_rewrite_fails_naming_file_line_and_label(label, message):
    with pytest.raises(regen.RegenError) as e:
        regen.rewrite_upstream_build(f'x = 1\ndeps = ["{label}"]\n', "sdk/rust/a/BUILD.bazel", {"sdk/rust/a"})
    assert str(e.value).startswith("sdk/rust/a/BUILD.bazel:2: ")
    assert label in str(e.value) and message in str(e.value)


@pytest.mark.parametrize("text, message", [
    # Loads regen.py has no mapping for.
    ('load("//build/bazel/rules/rust:defs.bzl", "rustc_library", "rustc_embed_files")\n',
     "f:1: loads rustc_embed_files from //build/bazel/rules/rust:defs.bzl"),
    ('load("//build/bazel/rules/fidl:fidl_library.bzl", "fidl_library", "fidl_cc")\n',
     "f:1: loads fidl_cc from //build/bazel/rules/fidl:fidl_library.bzl"),
    ('load("//build/bazel/rules/fidl:fidl_rust_library.bzl", "fidl_rust_library")\n',
     "f:1: load of //build/bazel/rules/fidl:fidl_rust_library.bzl: regen.py has no mapping"),
    ('load("@fuchsia_build_info//:args.bzl", "rust_cap_lints")\n',
     "f:1: loads rust_cap_lints from @fuchsia_build_info//:args.bzl"),
    # An unlisted package outside a //conditions:default branch.
    ('deps = select({"@platforms//os:fuchsia": ["//src/lib/emu"], "//conditions:default": []})\n',
     "f:1: depends on //src/lib/emu, but src/lib/emu is not listed"),
    ('load("@rules_rust//rust:defs.bzl", "rust_lint_config")\n',
     "f:1: loads rust_lint_config from @rules_rust//rust:defs.bzl"),
    ('load("@rules_rust//cargo:defs.bzl", "cargo_build_script")\n',
     "f:1: load of @rules_rust//cargo:defs.bzl"),
    # Rust rules that could not be marked vendored.
    ('x = 1\nrust_library(name = "x")\n', "f:2: rust_library() is not loaded from a rules file regen.py maps"),
    ('x = 1\nnative.rust_binary(name = "x")\n', "f:2: rust_binary() is not loaded"),
    ('load("//build/bazel/rules/rust:defs.bzl", "rustc_library")\nrustc_library(\n    name = "l",\n    vendored = False,\n)\n',
     "f:2: a Rust rule already sets vendored"),
    # Labels written other than as a plain double-quoted string.
    ("deps = ['//sdk/rust/b']\n", "f:1: label '//sdk/rust/b' is not a plain double-quoted string"),
    ('deps = ["""//sdk/rust/b"""]\n', "is not a plain double-quoted string"),
    ('deps = ["//sdk/rust/" "b"]\n', "is not a plain double-quoted string"),
    # Not parseable.
    ("rustc_library(\n", "f:1: cannot parse"),
])
def test_rewriter_fails_closed(text, message):
    with pytest.raises(regen.RegenError) as e:
        regen.rewrite_upstream_build(text, "f", {"sdk/rust/b"})
    assert message in str(e.value)


# Go (M7): upstream's fidlgen_rust BUILD files at the lock revision, abridged.
GO_BINARY = _HDR + """\
load("@platforms//host:constraints.bzl", "HOST_CONSTRAINTS")
load("//build/bazel/rules/host:defs.bzl", "go_binary_host_tool")

package(default_applicable_licenses = ["//:license"])

go_binary_host_tool(
    name = "fidlgen_rust",
    srcs = ["main.go"],
    target_compatible_with = HOST_CONSTRAINTS,
    visibility = [
        "//build/bazel/rules:__subpackages__",
    ],
    deps = [
        "//tools/fidl/fidlgen_rust/codegen",
        "//tools/fidl/lib/fidlgen",
    ],
)
"""

GO_CODEGEN = _HDR + """\
load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@platforms//host:constraints.bzl", "HOST_CONSTRAINTS")
load("//tools/fidl/lib/fidlgentest:fidlgentest_go_test.bzl", "fidlgentest_go_test")

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//visibility:public"],
)

go_library(
    name = "codegen",
    srcs = ["codegen.go"],
    embedsrcs = ["alias.tmpl"],
    importpath = "go.fuchsia.dev/fuchsia/tools/fidl/fidlgen_rust/codegen",
    target_compatible_with = HOST_CONSTRAINTS,
    deps = ["//tools/fidl/lib/fidlgen"],
)

fidlgentest_go_test(
    name = "fidlgen_rust_lib_tests",
    srcs = ["ir_test.go"],
    embed = [":codegen"],
    target_compatible_with = HOST_CONSTRAINTS,
    visibility = ["//tools:__pkg__"],
    deps = ["//third_party/golibs:github.com/google/go-cmp/cmp"],
)
"""

GO_LIB = _HDR + """\
load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")
load("//build/bazel/platforms:constraints.bzl", "HOST_OS_CONSTRAINTS")

package(
    default_applicable_licenses = ["//:license"],
    default_visibility = ["//visibility:public"],
)

go_library(
    name = "fidlgen",
    srcs = ["types.go"],
    importpath = "go.fuchsia.dev/fuchsia/tools/fidl/lib/fidlgen",
    target_compatible_with = HOST_OS_CONSTRAINTS,
)

go_test(
    name = "fidlgen_lib_test",
    srcs = ["types_test.go"],
    embed = [
        ":fidlgen",
    ],
    target_compatible_with = HOST_OS_CONSTRAINTS,
    deps = [
        "//third_party/golibs:github.com/google/go-cmp/cmp",
    ],
)
"""

GO_PATHS = {"tools/fidl/fidlgen_rust", "tools/fidl/fidlgen_rust/codegen", "tools/fidl/lib/fidlgen"}


def test_go_binary_host_tool_becomes_rules_go_go_binary():
    notes = []
    out = regen.rewrite_upstream_build(GO_BINARY, "tools/fidl/fidlgen_rust/BUILD.bazel", GO_PATHS, notes)
    assert notes == ["labels rewritten", "Go loads mapped"]
    # Only the load and the labels change; the call site keeps upstream's name.
    assert out == (GO_BINARY
                   .replace('load("//build/bazel/rules/host:defs.bzl", "go_binary_host_tool")',
                            'load("@io_bazel_rules_go//go:def.bzl", go_binary_host_tool = "go_binary")')
                   .replace('"//:license"', '"//vendor/fuchsia:license"')
                   .replace('"//build/bazel/rules:__subpackages__"',
                            '"//vendor/fuchsia/build/bazel/rules:__subpackages__"')
                   .replace('"//tools/', '"//vendor/fuchsia/tools/'))


def test_go_test_macros_are_dropped_with_their_load():
    notes = []
    out = regen.rewrite_upstream_build(GO_CODEGEN, "c/BUILD.bazel", GO_PATHS, notes)
    assert notes == ["labels rewritten", "Go loads mapped",
                     "test targets dropped: fidlgentest_go_test fidlgen_rust_lib_tests"]
    assert "fidlgentest" not in out and "golibs" not in out and "ir_test.go" not in out
    assert out.endswith('    deps = ["//vendor/fuchsia/tools/fidl/lib/fidlgen"],\n)\n')
    assert ('load("@io_bazel_rules_go//go:def.bzl", "go_library")\n'
            'load("@platforms//host:constraints.bzl", "HOST_CONSTRAINTS")\n\npackage(') in out


def test_go_test_is_dropped_and_host_os_constraints_mapped():
    out = regen.rewrite_upstream_build(GO_LIB, "l/BUILD.bazel", GO_PATHS)
    assert 'load("@io_bazel_rules_go//go:def.bzl", "go_library")\n' in out
    assert 'load("//rules:host.bzl", "HOST_OS_CONSTRAINTS")\n' in out
    assert "go_test" not in out and "golibs" not in out
    assert out.count("go_library(") == 1 and out.endswith("HOST_OS_CONSTRAINTS,\n)\n")


def test_rust_rules_keep_their_header_note():
    notes = []
    regen.rewrite_upstream_build(A_BUILD, "sdk/rust/a/BUILD.bazel", {"sdk/rust/a", "sdk/rust/b"}, notes)
    assert ", ".join(notes) == "labels rewritten, vendored = True added"


@pytest.mark.parametrize("text, message", [
    ('load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_source")\n',
     "f:1: loads go_source from @io_bazel_rules_go//go:def.bzl; regen.py maps only go_library, go_binary, go_test"),
    ('load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")\n',
     "f:1: load of @io_bazel_rules_go//proto:def.bzl: regen.py has no mapping"),
    ('load("//build/bazel/rules/host:defs.bzl", "py_binary_host_tool")\n',
     "f:1: loads py_binary_host_tool from //build/bazel/rules/host:defs.bzl"),
    ('load("//build/bazel/platforms:constraints.bzl", "HOST_CONSTRAINTS")\n',
     "f:1: loads HOST_CONSTRAINTS from //build/bazel/platforms:constraints.bzl"),
    ('x = 1\ngo_library(name = "x")\n', "f:2: go_library() is not loaded from a rules file regen.py maps"),
    ('load("@io_bazel_rules_go//go:def.bzl", "go_test")\n[go_test(name = n) for n in ["a"]]\n',
     "f:2: go_test() is dropped by regen.py, so it must be a top-level statement"),
    ('load("@io_bazel_rules_go//go:def.bzl", "go_test")\nx = go_test(name = "t")\n',
     "f:2: go_test() is dropped by regen.py"),
    ('load("@io_bazel_rules_go//go:def.bzl", "go_test")\ngo_test(name = NAME)\n',
     "f:2: go_test() is dropped by regen.py, so it needs a plain name"),
])
def test_go_rewriter_fails_closed(text, message):
    with pytest.raises(regen.RegenError) as e:
        regen.rewrite_upstream_build(text, "f", set())
    assert message in str(e.value)


def test_vendor_header_names_the_go_changes(env):
    upstream, repo, run = env
    _write(upstream, "tools/fidl/lib/fidlgen/BUILD.bazel", GO_LIB)
    _write(upstream, "tools/fidl/lib/fidlgen/types.go", "package fidlgen\n")
    _write(repo, "vendor/crates.txt", "sdk/rust/a upstream\nsdk/rust/b overlay\ntools/fidl/lib/fidlgen upstream\n")
    assert run("vendor") == 0
    text = (repo / "vendor/fuchsia/tools/fidl/lib/fidlgen/BUILD.bazel").read_text()
    assert text.startswith(f"# Generated by scripts/regen.py from fuchsia.git {REV}:tools/fidl/lib/fidlgen/BUILD.bazel\n"
                           "# (labels rewritten, Go loads mapped, test targets dropped: go_test fidlgen_lib_test). "
                           "Do not edit")
    assert (repo / "vendor/fuchsia/tools/fidl/lib/fidlgen/types.go").read_text() == "package fidlgen\n"
    assert run("--check") == 0


def test_vendored_added_to_every_form_of_call():
    text = ('load("//build/bazel/rules/rust:defs.bzl", "rustc_binary", "rustc_library", lib = "rustc_proc_macro")\n'
            'rustc_library(\n    name = "l",\n)\n\nrustc_binary(name = "b")\n\n'
            'rustc_library (\n    name = "spaced",\n)\n'
            '[lib(\n    name = n,\n    srcs = [f("(")],\n) for n in ["p"]]\n'
            '# rustc_library( in a comment\nx = "rustc_binary("\n')
    out = regen.rewrite_upstream_build(text, "f", set())
    assert out.count("vendored = True") == 4
    assert 'rustc_binary(vendored = True, name = "b")' in out
    assert "rustc_library (" + _MARK + '\n    name = "spaced",' in out
    assert "[lib(" + _MARK + "\n    name = n," in out
    assert 'lib = "rustc_proc_macro"' in out
    assert "# rustc_library( in a comment" in out and 'x = "rustc_binary("' in out


def test_overlay_checks():
    regen.check_overlay_build(B_OVERLAY, "o")
    with pytest.raises(regen.RegenError, match="o:6: rustc_library call without vendored = True"):
        regen.check_overlay_build(B_OVERLAY.replace("    vendored = True,\n", ""), "o")
    with pytest.raises(regen.RegenError, match="o:1: loads from @rules_rust//rust:defs.bzl"):
        regen.check_overlay_build('load("@rules_rust//rust:defs.bzl", "rust_library")\n', "o")
    with pytest.raises(regen.RegenError, match="o:1: rust_library\\(\\) is not loaded"):
        regen.check_overlay_build('rust_library(name = "x", vendored = True)\n', "o")
    with pytest.raises(regen.RegenError, match="not a plain double-quoted string"):
        regen.check_overlay_build("x = ['//vendor/fuchsia/sdk/rust/a']\n", "o")


def test_crate_build_rewrite_and_closure():
    text, deps = regen.rewrite_crate_build(
        _crate_build("foo", "1.0.0", ["//third_party/rust_crates/vendor/bar-0.2.0-rc.1:bar"]), "f")
    assert deps == {"vendor/bar-0.2.0-rc.1"}
    assert '"//vendor/bar-0.2.0-rc.1:bar"' in text
    assert '"@rules_rust//rust/platform:x86_64-unknown-fuchsia"' in text
    text, deps = regen.rewrite_crate_build(
        'deps = ["//third_party/rust_crates/ask2patch/memchr", "//third_party/rust_crates/forks/x-1:bs"]', "f")
    assert text == 'deps = ["//ask2patch/memchr", "//forks/x-1:bs"]'
    assert deps == {"ask2patch/memchr", "forks/x-1"}
    with pytest.raises(regen.RegenError, match="f:1: .*only crates.io crates"):
        regen.rewrite_crate_build('deps = ["//third_party/rust_crates/other/memchr"]', "f")
    with pytest.raises(regen.RegenError, match="f:1: .*unexpected label"):
        regen.rewrite_crate_build('deps = ["//sdk/rust/zx"]', "f")
    with pytest.raises(regen.RegenError, match="not a plain double-quoted string"):
        regen.rewrite_crate_build("deps = ['//third_party/rust_crates/vendor/x-1.0.0:x']", "f")


def test_vendor_list_parsing_errors():
    assert regen.read_vendor_list("a/b upstream\n\n# x\nc overlay # y\n") == [
        regen.Crate("a/b", "upstream"), regen.Crate("c", "overlay")]
    for bad, msg in [("a/b", "expected"), ("a/b copy", "expected"), ("/a upstream", "normalized"),
                     ("a/../b upstream", "normalized"), ("a/ upstream", "normalized"),
                     ("a upstream\na overlay", "listed twice")]:
        with pytest.raises(regen.RegenError, match=msg):
            regen.read_vendor_list(bad)


# --- end to end on the fake tree -------------------------------------------------------


def test_vendor_writes_the_expected_trees(env):
    upstream, repo, run = env
    assert run("vendor") == 0
    v = repo / "vendor/fuchsia"
    assert sorted(p.relative_to(v).as_posix() for p in v.rglob("*") if p.is_file()) == [
        "BUILD.bazel", "LICENSE", "PATENTS",
        "rustfmt.toml",
        "sdk/rust/a/BUILD.bazel", "sdk/rust/a/BUILD.gn", "sdk/rust/a/src/lib.rs", "sdk/rust/a/tool.sh",
        "sdk/rust/b/BUILD.bazel", "sdk/rust/b/BUILD.gn", "sdk/rust/b/src/lib.rs",
    ]
    # Copied byte for byte, modes kept; LICENSE covers the tree (C4).
    for rel in ("LICENSE", "PATENTS", "rustfmt.toml", "sdk/rust/a/src/lib.rs", "sdk/rust/b/src/lib.rs"):
        assert (v / rel).read_bytes() == (upstream / rel).read_bytes()
    assert (v / "sdk/rust/a/tool.sh").stat().st_mode & 0o111
    assert not (v / "sdk/rust/a/src/lib.rs").stat().st_mode & 0o111
    a = (v / "sdk/rust/a/BUILD.bazel").read_text()
    assert a.startswith(f"# Generated by scripts/regen.py from fuchsia.git {REV}:sdk/rust/a/BUILD.bazel\n")
    assert A_BUILD.splitlines()[0] in a  # upstream's own header is kept
    assert (v / "sdk/rust/b/BUILD.bazel").read_text() == B_OVERLAY
    root_build = (v / "BUILD.bazel").read_text()
    assert 'license_text = "LICENSE"' in root_build and "spdx:BSD-2-Clause" in root_build
    assert 'exports_files(\n    ["rustfmt.toml"],' in root_build
    assert "SPDX" not in root_build  # only REUSE.toml's vendor/fuchsia/** annotation applies

    c = repo / "third_party/crates"
    spec = json.loads((c / "crates.json").read_text())
    assert spec["aliases"] == ["foo"]  # baz is not used, so not fetched
    assert [(e["name"], e["version"], e["sha256"][:4], e["url"]) for e in spec["crates"] if "sha256" in e] == [
        ("bar", "0.2.0-rc.1", "2222", "https://static.crates.io/crates/bar/bar-0.2.0-rc.1.crate"),
        ("foo", "1.0.0", "1111", "https://static.crates.io/crates/foo/foo-1.0.0.crate"),
    ]
    # The patched crate reached through bar: copied, not downloaded (M6b).
    assert spec["crates"][0] == {
        "build_file": "BUILD.ask2patch.memo.bazel", "name": "memo", "path": "ask2patch/memo",
        "proc_macro": False, "target": "//ask2patch/memo:memo",
        "version": "2.0.0", "files": ["LICENSE-MIT", "gen.sh", "src/lib.rs"]}
    # The build list: every crate's library target, so //... builds them (M6b).
    build = (c / "BUILD.bazel").read_text()
    assert '"@rust_crates//vendor:foo",' in build and build.count('"@rust_crates//') == 4
    memo = c / "src/ask2patch/memo"
    for rel in ("LICENSE-MIT", "gen.sh", "src/lib.rs"):
        assert (memo / rel).read_bytes() == (upstream / "third_party/rust_crates/ask2patch/memo" / rel).read_bytes()
    assert (memo / "gen.sh").stat().st_mode & 0o111 and not (memo / "src/lib.rs").stat().st_mode & 0o111
    assert not (memo / "BUILD.bazel").exists()
    assert '"//ask2patch/memo:memo"' in (c / "BUILD.bar-0.2.0-rc.1.bazel").read_text()
    assert (c / "BUILD.ask2patch.memo.bazel").read_text().startswith(
        f"# Generated by scripts/regen.py from fuchsia.git {REV}:third_party/rust_crates/ask2patch/memo/BUILD.bazel\n")
    assert spec["cargo_lock"].endswith(f"{REV}:third_party/rust_crates/Cargo.lock")
    assert '"//vendor/bar-0.2.0-rc.1:bar"' in (c / "BUILD.foo-1.0.0.bazel").read_text()
    aliases = (c / "BUILD.vendor.bazel").read_text()
    assert 'name = "foo",\n    actual = "//vendor/foo-1.0.0:foo"' in aliases and '"baz"' not in aliases
    assert sorted(p.name for p in c.iterdir()) == [
        "BUILD.ask2patch.memo.bazel", "BUILD.bar-0.2.0-rc.1.bazel", "BUILD.bazel", "BUILD.foo-1.0.0.bazel",
        "BUILD.vendor.bazel", "crates.json", "src"]


def test_vendor_is_reproducible_and_removes_stale_files(env):
    _, repo, run = env
    assert run("vendor") == 0
    first = _snapshot(repo)
    _write(repo, "vendor/fuchsia/sdk/rust/a/stale.rs", "old\n")
    assert run("vendor") == 0
    assert _snapshot(repo) == first
    assert not any(p.name.endswith((".regen-new", ".regen-old")) for p in (repo / "vendor").iterdir())


def test_check_passes_on_a_clean_tree(env, capsys):
    _, repo, run = env
    assert run("vendor") == 0
    assert run("--check") == 0
    assert "match fuchsia.git" in capsys.readouterr().out


def test_check_names_a_one_byte_hand_edit(env, capsys):
    _, repo, run = env
    assert run("vendor") == 0
    f = repo / "vendor/fuchsia/sdk/rust/a/src/lib.rs"
    data = bytearray(f.read_bytes())
    data[-3] ^= 1  # "1" -> "0": one byte
    f.write_bytes(bytes(data))
    capsys.readouterr()
    assert run("--check") == 1
    err = capsys.readouterr().err
    assert "vendor/fuchsia/sdk/rust/a/src/lib.rs: content differs" in err
    assert "1 file(s) drift" in err


@pytest.mark.parametrize("change, expected", [
    (lambda r: (r / "vendor/fuchsia/sdk/rust/a/extra.rs").write_text("x"),
     "vendor/fuchsia/sdk/rust/a/extra.rs: not generated by regen.py"),
    (lambda r: (r / "vendor/fuchsia/PATENTS").unlink(), "vendor/fuchsia/PATENTS: missing"),
    (lambda r: (r / "vendor/fuchsia/sdk/rust/a/tool.sh").chmod(0o644),
     "vendor/fuchsia/sdk/rust/a/tool.sh: executable bit differs"),
    (lambda r: (r / "third_party/crates/crates.json").write_text("{}\n"),
     "third_party/crates/crates.json: content differs"),
])
def test_check_detects_other_drift(env, capsys, change, expected):
    _, repo, run = env
    assert run("vendor") == 0
    change(repo)
    capsys.readouterr()
    assert run("--check") == 1
    assert expected in capsys.readouterr().err


def test_check_detects_an_input_change(env, capsys):
    """Changing an overlay without rerunning vendor is drift too."""
    _, repo, run = env
    assert run("vendor") == 0
    ov = repo / "overlays/sdk/rust/b/BUILD.bazel"
    ov.write_text(ov.read_text() + "# changed\n")
    assert run("--check") == 1
    assert "vendor/fuchsia/sdk/rust/b/BUILD.bazel: content differs" in capsys.readouterr().err


# --- patched crates and crate roots (M6b) ---------------------------------------------


def test_crates_io_list_adds_roots_and_follows_patched_crates(env):
    """vendor/crates_io.txt adds aliases; a fork's self-label and its vendor deps are followed."""
    _, repo, run = env
    (repo / "vendor/crates_io.txt").write_text("# roots\nqux\n")
    assert run("vendor") == 0
    c = repo / "third_party/crates"
    spec = json.loads((c / "crates.json").read_text())
    assert spec["aliases"] == ["foo", "qux"]
    assert [e["path"] for e in spec["crates"]] == [
        "ask2patch/memo", "forks/qux-0.3.0", "vendor/bar-0.2.0-rc.1", "vendor/baz-0.1.0", "vendor/foo-1.0.0"]
    qux = (c / "BUILD.forks.qux-0.3.0.bazel").read_text()
    assert '"//forks/qux-0.3.0:build_script_build"' in qux and '"//vendor/baz-0.1.0:baz"' in qux
    assert 'name = "qux",\n    actual = "//forks/qux-0.3.0:qux"' in (c / "BUILD.vendor.bazel").read_text()


def test_in_tree_label_into_a_patched_crate_is_a_root(env):
    upstream, repo, run = env
    build = upstream / "sdk/rust/a/BUILD.bazel"
    build.write_text(build.read_text().replace(
        '"//third_party/rust_crates/vendor:foo",', '"//third_party/rust_crates/vendor:foo",\n'
        '        "//third_party/rust_crates/forks/qux-0.3.0:qux",'))
    assert run("vendor") == 0
    assert '"@rust_crates//forks/qux-0.3.0:qux"' in (repo / "vendor/fuchsia/sdk/rust/a/BUILD.bazel").read_text()
    spec = json.loads((repo / "third_party/crates/crates.json").read_text())
    assert "forks/qux-0.3.0" in [e["path"] for e in spec["crates"]]
    assert spec["aliases"] == ["foo"]


def test_check_names_a_one_byte_edit_in_a_patched_crate(env, capsys):
    _, repo, run = env
    assert run("vendor") == 0
    f = repo / "third_party/crates/src/ask2patch/memo/src/lib.rs"
    f.write_bytes(f.read_bytes().replace(b"memo", b"mema"))
    assert run("--check") == 1
    err = capsys.readouterr().err
    assert "third_party/crates/src/ask2patch/memo/src/lib.rs: content differs" in err
    assert "1 file(s) drift" in err


def test_crate_target_and_build_list():
    pm = _crate_build("m", "1.0.0").replace("rust_library(", "rust_proc_macro(").replace(
        '"@rules_rust//rust:defs.bzl", "rust_library"', '"@rules_rust//rust:defs.bzl", "rust_proc_macro"')
    assert regen.crate_target(pm, "f") == ("rust_proc_macro", "m")
    assert regen.crate_target(_crate_build("l", "1.0.0") + 'cargo_build_script(name = "_bs")\n', "f") == \
        ("rust_library", "l")
    with pytest.raises(regen.RegenError, match="f: expected one of rust_library, rust_proc_macro, found none"):
        regen.crate_target('cargo_build_script(name = "_bs")\n', "f")
    with pytest.raises(regen.RegenError, match="found rust_library\\(a\\), rust_library\\(b\\)"):
        regen.crate_target('rust_library(name = "a")\nrust_library(name = "b")\n', "f")
    build = regen.crates_build([
        {"target": "//vendor/l-1:l", "proc_macro": False},
        {"target": "//vendor/m-1:m", "proc_macro": True},
        {"target": "//vendor/n-1:n", "proc_macro": False},
    ], {"l": "//vendor/l-1:l", "m": "//vendor/m-1:m"})
    aliases, host = build.split('name = "aliases"')[1].split('name = "host_all"')
    assert '"@rust_crates//vendor:l",' in aliases and "incompatible" not in aliases
    assert '"vendor:m"' not in aliases and "n-1" not in aliases
    for label in ("//vendor/l-1:l", "//vendor/m-1:m", "//vendor/n-1:n"):
        assert f'"@rust_crates{label}",' in host
    assert '"@platforms//os:fuchsia": ["@platforms//:incompatible"]' in host
    assert "filegroup" not in regen.crates_build([], {})


def test_crates_io_list_parsing_errors():
    assert regen.read_crates_io_list("# c\nanyhow\n\nlibc  # patched\nzerocopy\n") == ["anyhow", "libc", "zerocopy"]
    for bad, msg in [("a b", "expected one alias name"), ("//x", "expected one alias name"),
                     ("a\na", "listed twice"), ("b\na", "out of order")]:
        with pytest.raises(regen.RegenError, match=msg):
            regen.read_crates_io_list(bad)


@pytest.mark.parametrize("edit, message", [
    (lambda up, repo: (repo / "vendor/crates_io.txt").unlink(), "vendor/crates_io.txt: missing"),
    (lambda up, repo: (repo / "vendor/crates_io.txt").write_text("nope\n"), "has no alias 'nope'"),
    (lambda up, repo: _write(up, "third_party/rust_crates/Cargo.lock",
                             CARGO_LOCK.replace(b'name = "memo"', b'name = "memo2"')) or make_repo(repo, up),
     "ask2patch/memo/BUILD.bazel: memo 2.0.0 is not a local (patched) package"),
    (lambda up, repo: _write(up, "third_party/rust_crates/ask2patch/memo/sub/BUILD", "# x\n"),
     "third_party/rust_crates/ask2patch/memo/sub/BUILD: a patched crate may not contain another BUILD"),
    (lambda up, repo: _write(up, "third_party/rust_crates/vendor/bar-0.2.0-rc.1/BUILD.bazel",
                             _crate_build("bar", "0.2.0-rc.1", ["//third_party/rust_crates/forks/gone:gone"])),
     "third_party/rust_crates/forks/gone/BUILD.bazel: no such file"),
])
def test_patched_crate_errors_name_the_input(env, capsys, edit, message):
    upstream, repo, run = env
    edit(upstream, repo)
    assert run("vendor") == 2
    assert message in capsys.readouterr().err
    assert not (repo / "third_party/crates").exists()


def _patch(old: str, new: str, path="sdk/rust/a/src/lib.rs") -> str:
    return (f"--- a/{path}\n+++ b/{path}\n@@ -1,3 +1,3 @@\n pub fn a() -> u32 {{\n"
            f"-    {old}\n+    {new}\n }}\n")


def test_patches_apply_in_name_order(env):
    _, repo, run = env
    _write(repo, "patches/fuchsia/sdk/rust/a/0001-two.patch", _patch("1", "2"))
    _write(repo, "patches/fuchsia/sdk/rust/a/0002-three.patch", _patch("2", "3"))
    assert run("vendor") == 0
    assert (repo / "vendor/fuchsia/sdk/rust/a/src/lib.rs").read_text() == "pub fn a() -> u32 {\n    3\n}\n"
    assert run("--check") == 0


def test_a_patch_that_does_not_apply_names_patch_and_file(env, capsys):
    _, repo, run = env
    assert run("vendor") == 0
    before = _snapshot(repo)
    _write(repo, "patches/fuchsia/sdk/rust/a/0001-stale.patch", _patch("7", "8"))
    assert run("vendor") == 2
    err = capsys.readouterr().err
    assert "patches/fuchsia/sdk/rust/a/0001-stale.patch: does not apply to " \
           "vendor/fuchsia/sdk/rust/a/src/lib.rs" in err
    assert _snapshot(repo) == before  # nothing replaced


def test_a_patch_for_a_missing_file_names_it(env, capsys):
    _, repo, run = env
    _write(repo, "patches/fuchsia/sdk/rust/a/0001-gone.patch", _patch("1", "2", "sdk/rust/a/src/gone.rs"))
    assert run("vendor") == 2
    assert "0001-gone.patch: does not apply to vendor/fuchsia/sdk/rust/a/src/gone.rs" in capsys.readouterr().err


def test_a_patch_may_touch_only_its_own_crate(env, capsys):
    _, repo, run = env
    _write(repo, "patches/fuchsia/sdk/rust/b/0001-wrong-place.patch", _patch("1", "2"))
    assert run("vendor") == 2
    assert ("patches/fuchsia/sdk/rust/b/0001-wrong-place.patch: patches under patches/fuchsia/sdk/rust/b/ "
            "may change only files of sdk/rust/b; this one changes sdk/rust/a/src/lib.rs") in capsys.readouterr().err


@pytest.mark.parametrize("edit, message", [
    (lambda up, repo: (repo / "vendor/crates.txt").write_text("sdk/rust/a upstream\n"),
     "sdk/rust/b is not listed in vendor/crates.txt"),
    (lambda up, repo: ((repo / "vendor/crates.txt").write_text("sdk/rust/a upstream\nsdk/rust/b upstream\n"),
                       (repo / "overlays/sdk/rust/b/BUILD.bazel").unlink()),
     "sdk/rust/b is 'upstream', but upstream has no BUILD.bazel"),
    (lambda up, repo: (repo / "vendor/crates.txt").write_text("sdk/rust/a upstream\nsdk/rust/b upstream\n"),
     "overlays/sdk/rust/b/BUILD.bazel exists, but vendor/crates.txt says 'upstream'"),
    (lambda up, repo: (repo / "overlays/sdk/rust/b/BUILD.bazel").unlink(),
     "overlays/sdk/rust/b/BUILD.bazel does not exist"),
    (lambda up, repo: _write(repo, "overlays/sdk/rust/a/BUILD.bazel", B_OVERLAY),
     "overlays/sdk/rust/a/BUILD.bazel exists, but vendor/crates.txt says 'upstream'"),
    (lambda up, repo: _write(up, "third_party/rust_crates/Cargo.lock", CARGO_LOCK + b"\n"),
     "third_party/rust_crates/Cargo.lock: SHA-256"),
    (lambda up, repo: _write(up, "third_party/rust_crates/Cargo.lock", CARGO_LOCK.replace(b'"bar"', b'"bar2"'))
     or make_repo(repo, up),
     "bar 0.2.0-rc.1 is not a crates.io package"),
    (lambda up, repo: _write(up, "third_party/rust_crates/vendor/BUILD.bazel", ALIASES.replace('"foo"', '"foo2"')),
     "has no alias 'foo'"),
    (lambda up, repo: (repo / "vendor/crates.txt").write_text("sdk/rust/a upstream\nsdk/rust/b overlay\nsdk/x upstream\n"),
     "sdk/x: no such directory"),
    (lambda up, repo: _write(repo, "overlays/sdk/rust/c/BUILD.bazel", B_OVERLAY),
     "overlays/sdk/rust/c/BUILD.bazel: sdk/rust/c is not listed in vendor/crates.txt"),
    (lambda up, repo: _write(repo, "patches/fuchsia/sdk/rust/c/0001-x.patch", _patch("1", "2")),
     "patches/fuchsia/sdk/rust/c/0001-x.patch: sdk/rust/c is not listed in vendor/crates.txt"),
    (lambda up, repo: _write(repo, "patches/fuchsia/sdk/rust/a/0001-x.diff", _patch("1", "2")),
     "patches/fuchsia/sdk/rust/a/0001-x.diff: not a patch"),
    (lambda up, repo: _write(repo, "overlays/sdk/rust/b/BUILD", B_OVERLAY),
     "overlays/sdk/rust/b/BUILD: not an overlay"),
])
def test_input_errors_name_the_input(env, capsys, edit, message):
    upstream, repo, run = env
    edit(upstream, repo)
    assert run("vendor") == 2
    assert message in capsys.readouterr().err
    assert not (repo / "vendor/fuchsia").exists()


def test_needs_a_stage_or_check(env):
    _, _, run = env
    with pytest.raises(SystemExit):
        run()


# --- the git source, against a local repository (no network) -------------------------


def _git(*args, cwd):
    return subprocess.run(["git", *args], cwd=cwd, check=True, capture_output=True).stdout.decode().strip()


@pytest.fixture
def git_upstream(tmp_path):
    src = make_upstream(tmp_path / "src")
    _git("init", "-q", cwd=src)
    _git("config", "uploadpack.allowFilter", "true", cwd=src)
    _git("config", "uploadpack.allowAnySHA1InWant", "true", cwd=src)
    _git("add", ".", cwd=src)
    _git("-c", "user.name=t", "-c", "user.email=t@example.invalid", "-c", "commit.gpgsign=false",
         "commit", "-q", "-m", "one", cwd=src)
    return src, _git("rev-parse", "HEAD", cwd=src)


def test_git_source_reads_files_and_modes(git_upstream, tmp_path):
    src, rev = git_upstream
    s = regen.GitSource(src.as_uri(), rev, tmp_path / "work")
    files = s.files("sdk/rust/a")
    assert files["sdk/rust/a/tool.sh"] == 0o755 and files["sdk/rust/a/src/lib.rs"] == 0o644
    assert "sdk/rust/a/nested/src/lib.rs" in files
    got = s.read(["LICENSE", "sdk/rust/a/src/lib.rs", "LICENSE"])
    assert got["sdk/rust/a/src/lib.rs"] == (src / "sdk/rust/a/src/lib.rs").read_bytes()
    assert got["LICENSE"] == b"Fuchsia license text\n"
    with pytest.raises(regen.RegenError, match="no such directory"):
        s.files("sdk/rust/nope")
    with pytest.raises(regen.RegenError, match="no such file"):
        s.read(["sdk/rust/nope.rs"])
    # "sdk/rust/a" must not match "sdk/rust/ab".
    assert all(f.startswith("sdk/rust/a/") for f in files)


def test_existing_reports_files_only(git_upstream, tmp_path):
    """Source.existing (used by closure.py, M6): files present at the revision."""
    src, rev = git_upstream
    want = ["LICENSE", "sdk/rust/a/src/lib.rs", "sdk/rust/a", "sdk/rust/nope.rs", "sdk/rust/a/nested/src/lib.rs"]
    expected = {"LICENSE", "sdk/rust/a/src/lib.rs", "sdk/rust/a/nested/src/lib.rs"}
    git = regen.GitSource(src.as_uri(), rev, tmp_path / "work")
    assert git.existing(want) == expected
    assert git.read(sorted(expected))["LICENSE"] == b"Fuchsia license text\n"
    assert regen.DirSource(src, rev).existing(want) == expected


def test_git_source_unknown_revision_fails(git_upstream, tmp_path):
    src, _ = git_upstream
    with pytest.raises(regen.RegenError, match="fetch"):
        regen.GitSource(src.as_uri(), "0" * 40, tmp_path / "work")


def test_vendor_from_git_matches_vendor_from_directory(git_upstream, tmp_path):
    src, rev = git_upstream
    repo_git = make_repo(tmp_path / "r1", src)
    repo_dir = make_repo(tmp_path / "r2", src)
    for repo in (repo_git, repo_dir):
        lock = json.loads((repo / "overlay.lock.json").read_text())
        lock["fuchsia_revision"]["value"] = rev
        (repo / "overlay.lock.json").write_text(json.dumps(lock))
    assert regen.main(["vendor"], root=repo_git,
                      make_source=lambda r: regen.GitSource(src.as_uri(), r, tmp_path / "w")) == 0
    assert regen.main(["vendor"], root=repo_dir, make_source=lambda r: regen.DirSource(src, r)) == 0
    snap = {k: v for k, v in _snapshot(repo_git).items()}
    assert snap == _snapshot(repo_dir) and snap


# --- FIDL libraries and the M8 mappings --------------------------------------------

# Upstream's sdk/fidl/fuchsia.mem/BUILD.bazel and zircon/vdso/zx/BUILD.bazel at the lock
# revision, abridged.
FIDL_MEM = _HDR + '''\
load("//build/bazel/rules/fidl:fidl_library.bzl", "fidl_library")

fidl_library(
    name = "fuchsia.mem",
    srcs = [
        "buffer.fidl",
        "range.fidl",
    ],
    category = "partner",
    stable = True,
    visibility = ["//visibility:public"],
    deps = ["//zircon/vdso/zx"],
)
'''

FIDL_ZX = _HDR + '''\
load("//build/bazel/rules/fidl:fidl_library.bzl", "fidl_library")

fidl_library(
    name = "zx",
    srcs = [
        "//zircon/vdso:overview.fidl",
        "//zircon/vdso:rights.fidl",
    ],
    api_file_path = "//sdk/fidl/zx:zx.api",
    enable_rust = False,
    versioned = "fuchsia",
)
'''

FIDL_PATHS = {"sdk/fidl/fuchsia.mem", "zircon/vdso/zx"}


def test_idk_library_takes_its_sources_from_the_idk():
    out = regen.rewrite_upstream_build(FIDL_MEM, "sdk/fidl/fuchsia.mem/BUILD.bazel", FIDL_PATHS, idk=True)
    assert 'load("//rules:fidl.bzl", "fidl_library")' in out
    assert '"@fuchsia_sdk//fidl/fuchsia.mem:buffer.fidl",\n        "@fuchsia_sdk//fidl/fuchsia.mem:range.fidl",' in out
    assert 'deps = ["//vendor/fuchsia/zircon/vdso/zx"]' in out


def test_idk_library_sources_given_as_labels_and_api_file_path():
    notes = []
    out = regen.rewrite_upstream_build(FIDL_ZX, "zircon/vdso/zx/BUILD.bazel", FIDL_PATHS, notes, idk=True)
    assert '"@fuchsia_sdk//fidl/zx:overview.fidl",\n        "@fuchsia_sdk//fidl/zx:rights.fidl",' in out
    assert "api_file_path = None," in out
    assert notes == ["labels rewritten", "sources from the IDK"]


def test_upstream_fidl_library_keeps_its_own_sources():
    notes = []
    out = regen.rewrite_upstream_build(FIDL_MEM, "sdk/fidl/fuchsia.mem/BUILD.bazel", FIDL_PATHS, notes)
    assert '"buffer.fidl",\n        "range.fidl",' in out
    assert notes == ["labels rewritten", "FIDL load mapped"]


@pytest.mark.parametrize("text, message", [
    ('load("//build/bazel/rules/rust:defs.bzl", "rustc_library")\n', "must load fidl_library"),
    ('load("//build/bazel/rules/fidl:fidl_library.bzl", "fidl_library")\nfidl_library(srcs = ["a.fidl"])\n',
     "f:2: fidl_library() without a plain name or library_name"),
    ('load("//build/bazel/rules/fidl:fidl_library.bzl", "fidl_library")\nfidl_library(name = "x", srcs = S)\n',
     'f:2: fidl_library() of an IDK library needs srcs'),
    ('load("//build/bazel/rules/fidl:fidl_library.bzl", "fidl_library")\n'
     'fidl_library(name = "x", srcs = ["a" + ".fidl"])\n', "f:2: srcs entry is not a plain string"),
])
def test_idk_library_errors(text, message):
    with pytest.raises(regen.RegenError) as e:
        regen.rewrite_upstream_build(text, "f", set(), idk=True)
    assert message in str(e.value)


def test_rustc_test_is_dropped_with_its_calls_and_from_the_load():
    text = _HDR + '''\
load("//build/bazel/rules/rust:defs.bzl", "rustc_library", "rustc_test")

rustc_library(
    name = "l",
    srcs = ["src/lib.rs"],
)

rustc_test(
    name = "l_test",
    srcs = ["src/lib.rs"],
    deps = ["//third_party/rust_crates/vendor:anyhow"],
)
'''
    notes = []
    out = regen.rewrite_upstream_build(text, "f", set(), notes)
    assert 'load("//rules:rustc.bzl", "rustc_library")' in out
    assert "rustc_test" not in out and "anyhow" not in out
    assert "test targets dropped: rustc_test l_test" in notes


def test_only_rustc_test_loaded_removes_the_load():
    text = 'load("//build/bazel/rules/rust:defs.bzl", "rustc_test")\n\nrustc_test(name = "t")\n'
    assert regen.rewrite_upstream_build(text, "f", set()).strip() == ""


def test_build_arguments_map_to_the_overlays():
    text = ('load("@fuchsia_build_info//:args.bzl", "fuchsia_sync_detect_lock_cycles")\n'
            'x = [] if fuchsia_sync_detect_lock_cycles else ["//sdk/rust/b"]\n')
    out = regen.rewrite_upstream_build(text, "f", {"sdk/rust/b"})
    assert out.startswith('load("//rules:build_info.bzl", "fuchsia_sync_detect_lock_cycles")\n')


def test_build_info_args_are_the_ones_the_overlay_defines():
    text = (ROOT / "rules/build_info.bzl").read_text()
    defined = sorted(line.split(" =")[0] for line in text.splitlines()
                     if line and not line.startswith(("#", " ", '"')) and " = " in line)
    assert defined == sorted(regen.BUILD_INFO_ARGS)


def test_sdk_libraries_and_fidl_rules_visibility():
    text = ('deps = ["//sdk/lib/fdio", "//zircon/system/ulib/sync"]\n'
            'visibility = ["//build/bazel/rules/fidl:__subpackages__", "//build/bazel/rules/fidl:__pkg__"]\n')
    out = regen.rewrite_upstream_build(text, "f", set())
    assert '"@fuchsia_sdk//pkg/fdio", "@fuchsia_sdk//pkg/sync"' in out
    assert '"//rules:__subpackages__", "//rules:__pkg__"' in out


HOST_BRANCH = _HDR + '''\
load("//build/bazel/rules/rust:defs.bzl", "rustc_library")

rustc_library(
    name = "a",
    srcs = ["src/lib.rs"],
    deps = select({
        "@platforms//os:fuchsia": ["//sdk/rust/b"],
        "//conditions:default": ["//src/lib/emulated"],
    }),
)
'''


def test_unlisted_label_in_a_default_branch_is_provisional():
    provisional = []
    out = regen.rewrite_upstream_build(HOST_BRANCH, "sdk/rust/a/BUILD.bazel", {"sdk/rust/b"},
                                       provisional=provisional)
    assert '"//conditions:default": ["//vendor/fuchsia/src/lib/emulated"]' in out
    assert provisional == [("sdk/rust/a/BUILD.bazel:12", "//vendor/fuchsia/src/lib/emulated")]
    with pytest.raises(regen.RegenError) as e:
        regen.rewrite_upstream_build(HOST_BRANCH, "f", {"sdk/rust/b"})
    assert "f:12: depends on //src/lib/emulated, but src/lib/emulated is not listed" in str(e.value)


def _host_branch_env(env):
    upstream, repo, run = env
    _write(upstream, "sdk/rust/a/BUILD.bazel", HOST_BRANCH)
    return upstream, repo, run


def test_a_provisional_label_left_after_the_patches_fails(env, capsys):
    _, repo, run = _host_branch_env(env)
    assert run("vendor") == 2
    err = capsys.readouterr().err
    assert ("sdk/rust/a/BUILD.bazel:12: depends on //src/lib/emulated in a //conditions:default "
            "branch, but src/lib/emulated is not listed in vendor/crates.txt; list it, or remove "
            "the branch with a patch under patches/fuchsia/sdk/rust/a/") in err


def test_a_patch_removing_the_provisional_label_passes(env):
    _, repo, run = _host_branch_env(env)
    path = "sdk/rust/a/BUILD.bazel"
    before = (regen._header(REV, path, "labels rewritten, vendored = True added")
              + regen.rewrite_upstream_build(HOST_BRANCH, path, {"sdk/rust/a", "sdk/rust/b"}, provisional=[]))
    after = before.replace('["//vendor/fuchsia/src/lib/emulated"]', "[]")
    patch = "".join(difflib.unified_diff(before.splitlines(keepends=True), after.splitlines(keepends=True),
                                         f"a/{path}", f"b/{path}"))
    _write(repo, "patches/fuchsia/sdk/rust/a/0001-fuchsia-only.patch", patch)
    assert run("vendor") == 0
    assert '"//conditions:default": [],' in (repo / "vendor/fuchsia" / path).read_text()
    assert run("--check") == 0


def test_idk_mode_copies_only_the_build_file(env):
    upstream, repo, run = env
    _write(upstream, "sdk/fidl/fuchsia.mem/BUILD.bazel", FIDL_MEM)
    _write(upstream, "sdk/fidl/fuchsia.mem/buffer.fidl", "library fuchsia.mem;\n")
    _write(upstream, "sdk/fidl/fuchsia.mem/OWNERS", "x\n")
    _write(upstream, "zircon/vdso/zx/BUILD.bazel", FIDL_ZX)
    _write(repo, "vendor/crates.txt", "sdk/fidl/fuchsia.mem idk\nsdk/rust/a upstream\n"
                                      "sdk/rust/b overlay\nzircon/vdso/zx idk\n")
    assert run("vendor") == 0
    lib = repo / "vendor/fuchsia/sdk/fidl/fuchsia.mem"
    assert sorted(p.name for p in lib.iterdir()) == ["BUILD.bazel"]
    assert "(labels rewritten, sources from the IDK)" in (lib / "BUILD.bazel").read_text()
    assert run("--check") == 0


def test_idk_mode_needs_an_upstream_build_file(env, capsys):
    upstream, repo, run = env
    _write(upstream, "sdk/fidl/fuchsia.x/x.fidl", "library fuchsia.x;\n")
    _write(repo, "vendor/crates.txt", "sdk/fidl/fuchsia.x idk\nsdk/rust/a upstream\nsdk/rust/b overlay\n")
    assert run("vendor") == 2
    assert "sdk/fidl/fuchsia.x is 'idk', but upstream has no BUILD.bazel there" in capsys.readouterr().err


def test_an_aliased_rustc_test_is_not_noted_as_a_go_change():
    text = ('load("//build/bazel/rules/rust:defs.bzl", "rustc_library", my_test = "rustc_test")\n\n'
            'rustc_library(name = "l")\n\nmy_test(name = "t")\n')
    notes = []
    out = regen.rewrite_upstream_build(text, "f", set(), notes)
    assert "my_test" not in out
    assert notes == ["labels rewritten", "vendored = True added", "test targets dropped: my_test t"]


def test_build_arguments_are_noted_in_the_header():
    notes = []
    regen.rewrite_upstream_build('load("@fuchsia_build_info//:args.bzl", "fuchsia_sync_detect_lock_cycles")\n',
                                 "f", set(), notes)
    assert "build arguments from //rules:build_info.bzl" in notes
