# SPDX-FileCopyrightText: 2026 Curtis Galloway
# SPDX-License-Identifier: Apache-2.0
"""Tests for scripts/resolve_pins.py. All network access goes through a stub Upstream."""

from __future__ import annotations

import base64
import hashlib
import json
import os
import struct
import subprocess
from pathlib import Path

import pytest

import resolve_pins as rp

V = "33.20260927.4.1"
FX = "b5274053cc0f1ba03cd0902a3da575ac9c31c152"
INTEG = "1463df67e630ab75428ad5731ab1c24dd5dce1a9"
BUILDS = ["8669503301662913841", "8669503301662913825", "8669503301662913777"]
RUST_PIN = "git_revisions:c26ce708de5d14682647895d2f3caf38f70b5aa6,3493720eca95cf844a8d7e58fdd12e0e5644e7d0"
HOST_ID = "3a8ffdbed3f78ba359e5e9a4677a5d27c8e13d9c4822243bf78b16a57acb225f"
TARGET_ID = "4fe0f40e20ce02113705648c7123afcee4294c7d5e98459bf1e5c0204f07d603"
HOST_STD_ID = "1db7ec26634d13d7403dae922ff1fab093b2fa4df082a82a9036af289a72d40e"
CLANG_PIN = "git_revision:3493720eca95cf844a8d7e58fdd12e0e5644e7d0"
CLANG_ID = "d37d515293218c424ea50a13037b6a897d032c963b8de4d9ab470e3de7d42e2d"
IDK_CIPD_ID = "41d82a3f4dbf718a5141040d36e463b218a49c97837b964a5f2a86ab6624a8a9"
RULES_ID = "8d346b9a21a6c3c0d4e6ffc40e9ef0f81e9545dd75040b068d4fa09d74f54845"
GO_PIN = "git_revision:14265db9dd19d6adc2c59f6e4f609d4f5a251442"
GO_ID = "4f8a8a8e7315660fe818a2ef914ff333433a87f7345d147b8a8291d8095b0d61"
IDK_BYTES = b"not really a tarball"
CARGO_LOCK = b"# This file is automatically @generated by Cargo.\nversion = 4\n"

TOOLCHAIN_XML = b"""<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <packages>
    <package name="fuchsia/third_party/lldb/${platform}"
             version="git_revision:0f61051f541a5b8cfce25c84262dfdbadb9ca688"
             platforms="linux-amd64,mac-amd64"
             path="prebuilt/third_party/lldb/{{.OS}}-{{.Arch}}"/>
    <package name="fuchsia/third_party/clang/${platform}"
             version="%(clang)s"
             platforms="linux-amd64,linux-arm64,mac-amd64,mac-arm64,windows-amd64"
             path="prebuilt/third_party/clang/{{.OS}}-{{.Arch}}"/>
    <package name="fuchsia/third_party/clang/linux-arm64"
             version="%(clang)s"
             platforms="linux-amd64"
             attributes="clang-arm64"
             path="prebuilt/third_party/clang/linux-arm64"/>
    <package name="fuchsia/go/${platform}"
             version="%(go)s"
             platforms="linux-amd64,linux-arm64"
             path="prebuilt/third_party/go/{{.OS}}-{{.Arch}}"/>
    <package name="fuchsia/third_party/rust/host/${platform}"
             version="%(pin)s"
             platforms="linux-amd64,linux-arm64,mac-amd64,mac-arm64,windows-amd64"
             path="prebuilt/third_party/rust/{{.OS}}-{{.Arch}}"/>
    <package name="fuchsia/third_party/rust/target/fuchsia"
             version="%(pin)s"
             platforms="linux-amd64,linux-arm64,mac-amd64,mac-arm64"
             path="prebuilt/third_party/rust/{{.OS}}-{{.Arch}}"/>
    <package name="fuchsia/third_party/rust/target/aarch64-apple-darwin"
             version="%(pin)s"
             platforms="linux-amd64,linux-arm64,mac-amd64,mac-arm64"
             path="prebuilt/third_party/rust/{{.OS}}-{{.Arch}}"/>
    <package name="fuchsia/third_party/rust/target/x86_64-unknown-linux-gnu"
             version="%(pin)s"
             platforms="linux-amd64,linux-arm64,mac-amd64,mac-arm64"
             path="prebuilt/third_party/rust/{{.OS}}-{{.Arch}}"/>
  </packages>
</manifest>
""" % {b"pin": RUST_PIN.encode(), b"clang": CLANG_PIN.encode(), b"go": GO_PIN.encode()}

GCS = "https://storage.googleapis.com"
PB_URL = f"{GCS}/fuchsia/development/{V}/product_bundles.json"
IDK_URL = f"{GCS}/fuchsia/development/{V}/sdk/linux-amd64/core.tar.gz"
IDK_META_URL = f"{GCS}/storage/v1/b/fuchsia/o/development%2F{V}%2Fsdk%2Flinux-amd64%2Fcore.tar.gz"


PB_BUCKET = f"{GCS}/fuchsia-public-artifacts-release"
TRANSFER_GS = f"gs://fuchsia-public-artifacts-release/builds/{BUILDS[1]}/product_bundles/core.x64/transfer.json"
TRANSFER_URL = f"{PB_BUCKET}/builds/{BUILDS[1]}/product_bundles/core.x64/transfer.json"
BLOB_A, BLOB_B = "a" * 64, "b" * 64
# Bundle path -> (URL, bytes), as the transfer manifest below lays them out.
BUNDLE_FILES = {
    f"blobs/1/{BLOB_A}": (f"{PB_BUCKET}/blobs/1/{BLOB_A}", b"blob a"),
    f"blobs/1/{BLOB_B}": (f"{PB_BUCKET}/blobs/1/{BLOB_B}", b"blob b"),
    "product_bundle.json": (f"{PB_BUCKET}/builds/{BUILDS[1]}/product_bundles/core.x64/product_bundle.json", b"{}"),
    "system_a/fuchsia.zbi": (f"{PB_BUCKET}/builds/{BUILDS[1]}/product_bundles/core.x64/system_a/fuchsia.zbi", b"zbi"),
}


def transfer_manifest() -> dict:
    return {"version": "1", "entries": [
        {"type": "blobs", "local": "product_bundle/blobs/1", "remote": "blobs/1",
         "entries": [{"name": BLOB_A}, {"name": BLOB_B}]},
        {"type": "files", "local": "product_bundle",
         "remote": f"builds/{BUILDS[1]}/product_bundles/core.x64",
         "entries": [{"name": "product_bundle.json"}, {"name": "system_a/fuchsia.zbi"}]},
    ]}


def expected_bundle_digest() -> str:
    # The definition, written out independently of rp.bundle_digest.
    lines = "".join(f"{p}\t{hashlib.sha256(b).hexdigest()}\n" for p, (_, b) in sorted(BUNDLE_FILES.items()))
    return hashlib.sha256(lines.encode()).hexdigest()


FIDLGEN_LABEL = "//tools/fidl/fidlgen_rust_next:fidlgen_rust_next.actual(//build/toolchain:host_x64)"
FIDLGEN_NOVARIANT = FIDLGEN_LABEL.replace("host_x64)", "host_x64-novariant)")
FIDLGEN_ID = "ad8c417e211deb69e793b2d354c96c310416fc3c"
FIDLGEN_URL = f"{PB_BUCKET}/buildid/{FIDLGEN_ID}/executable"


def make_elf(build_ids=(FIDLGEN_ID,), machine: int = 62, elf_class: int = 2, note_type: int = 3,
             note_name: bytes = b"GNU\0", truncate_note: bool = False) -> bytes:
    """A minimal little-endian ELF: a header, one SHT_NOTE section per build ID, and the
    section header table (a null section first, as linkers write it)."""
    notes = []
    for bid in build_ids:
        desc = bytes.fromhex(bid)
        notes.append(struct.pack("<III", len(note_name), len(desc), note_type) + note_name
                     + b"\0" * (-len(note_name) % 4) + desc + b"\0" * (-len(desc) % 4))
    body_off = 64
    body = b"".join(notes)
    shoff = body_off + len(body)
    sections = [bytes(64)]
    off = body_off
    for n in notes:
        size = len(n) + (10000 if truncate_note else 0)
        sections.append(struct.pack("<IIQQQQIIQQ", 1, 7, 2, 0, off, size, 0, 0, 4, 0))
        off += len(n)
    header = (b"\x7fELF" + bytes([elf_class, 1, 1, 0]) + bytes(8)
              + struct.pack("<HHIQQQIHHHHHH", 3, machine, 1, 0, 0, shoff, 0, 64, 56, 0, 64, len(sections), 0))
    assert len(header) == 64
    return header + body + b"".join(sections)


FIDLGEN_BYTES = make_elf()


def bid_url(build: str) -> str:
    return f"{PB_BUCKET}/builds/{build}/build-ids.json"


def sm_url(build: str) -> str:
    return f"{GCS}/fuchsia-public-artifacts-release/builds/{build}/source_manifest.json"


def source_manifest(fx: str = FX, integ: str = INTEG) -> dict:
    return {"directories": {
        ".": {"git_checkout": {"repo_url": "https://fuchsia.googlesource.com/fuchsia", "revision": fx}},
        "integration": {"git_checkout": {"repo_url": "https://example.invalid/integration", "revision": integ}},
    }}


class Stub:
    """An Upstream whose replies are plain dicts, so each test can break one lookup."""

    def __init__(self):
        self.gets: dict[str, object] = {
            PB_URL: [
                {"name": n, "product_version": V,
                 "transfer_manifest_url": f"gs://fuchsia-public-artifacts-release/builds/{b}/product_bundles/{n}/transfer.json"}
                for b, n in zip(BUILDS, ["core.vim3", "core.x64", "minimal.arm64"])
            ],
            **{sm_url(b): source_manifest() for b in BUILDS},
            TRANSFER_URL: transfer_manifest(),
            # core.vim3 (BUILDS[0]) builds only the host_x64-novariant copy, as in the release.
            bid_url(BUILDS[0]): {"fb62c8a7ab3bbf845669931fc902ef7a2f22ea47": FIDLGEN_NOVARIANT,
                                 "1" * 40: "//src/foo:bar(//build/toolchain/fuchsia:arm64)"},
            bid_url(BUILDS[1]): {FIDLGEN_ID: FIDLGEN_LABEL, "2" * 40: "//src/foo:bar(//build/toolchain:host_x64)"},
            bid_url(BUILDS[2]): {FIDLGEN_ID: FIDLGEN_LABEL},
            FIDLGEN_URL: FIDLGEN_BYTES,
            IDK_META_URL: {"size": str(len(IDK_BYTES)),
                           "md5Hash": base64.b64encode(hashlib.md5(IDK_BYTES).digest()).decode()},
        }
        # (package, version) -> instance hex digest, or an int HTTP status to fail with.
        self.cipd: dict[tuple[str, str], object] = {
            ("fuchsia/sdk/core/linux-amd64", f"version:{V}"): IDK_CIPD_ID,
            ("fuchsia/third_party/rust/host/linux-amd64", RUST_PIN): HOST_ID,
            ("fuchsia/third_party/rust/target/fuchsia", RUST_PIN): TARGET_ID,
            ("fuchsia/third_party/rust/target/x86_64-unknown-linux-gnu", RUST_PIN): HOST_STD_ID,
            ("fuchsia/third_party/clang/linux-amd64", CLANG_PIN): CLANG_ID,
            ("fuchsia/go/linux-amd64", GO_PIN): GO_ID,
            ("fuchsia/development/rules_fuchsia", f"git_revision:{INTEG}"): RULES_ID,
            ("fuchsia/development/rules_fuchsia", f"version:{V}"): RULES_ID,
        }
        self.tags: dict[tuple[str, str], list[dict]] = {
            ("fuchsia/sdk/core/linux-amd64", IDK_CIPD_ID): [
                {"key": "git_revision", "value": INTEG}, {"key": "version", "value": V}],
        }
        self.digests: dict[str, object] = {IDK_URL: IDK_BYTES,
                                           **{url: data for url, data in BUNDLE_FILES.values()}}
        self.git: dict[str, object] = {"manifests/toolchain": TOOLCHAIN_XML,
                                       "third_party/rust_crates/Cargo.lock": CARGO_LOCK}
        self.git_error: str | None = None
        self.calls: list[tuple] = []

    def get(self, url):
        self.calls.append(("get", url))
        reply = self.gets.get(url, 404)
        if isinstance(reply, int):
            raise rp.FetchError(f"GET {url}: HTTP {reply}", reply)
        return reply if isinstance(reply, bytes) else json.dumps(reply).encode()

    def post_json(self, url, payload):
        self.calls.append(("post", url, json.dumps(payload, sort_keys=True)))
        assert url.startswith("https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/")
        method, package = url.rsplit("/", 1)[1], payload["package"]
        if method == "ResolveVersion":
            reply = self.cipd.get((package, payload["version"]), 404)
            if isinstance(reply, int):
                raise rp.FetchError(f"HTTP {reply} no such tag", reply)
            if isinstance(reply, bytes):  # a raw, possibly malformed, reply body
                return b")]}'\n" + reply
            body = {"package": package, "instance": {"hashAlgo": "SHA256", "hexDigest": reply}}
        elif method == "DescribeInstance":
            assert payload["describeTags"] is True
            tags = self.tags.get((package, payload["instance"]["hexDigest"]), [])
            if isinstance(tags, bytes):
                return b")]}'\n" + tags
            body = {"instance": payload["instance"], "tags": tags}
        else:
            raise AssertionError(method)
        return b")]}'\n" + json.dumps(body).encode()

    def digest(self, url):
        self.calls.append(("digest", url))
        data = self.digests.get(url, 404)
        if isinstance(data, Exception):
            raise data
        if isinstance(data, int):
            raise rp.FetchError(f"GET {url}: HTTP {data}", data)
        return rp.Digest(hashlib.sha256(data).hexdigest(), hashlib.md5(data).hexdigest(), len(data))

    def git_show(self, repo, revision, path):
        # Like LiveUpstream: a fetch failure or a missing path raises FetchError.
        self.calls.append(("git", repo, revision, path))
        assert repo == "https://fuchsia.googlesource.com/fuchsia"
        if self.git_error:
            raise rp.FetchError(self.git_error)
        if path not in self.git:
            raise rp.FetchError(f"git cat-file -p {revision}:{path}: fatal: path '{path}' does not exist")
        return self.git[path]


def run(stub: Stub, out: Path, version: str = V) -> int:
    return rp.main([version, "--out", str(out)], upstream=stub)


# --- happy path ----------------------------------------------------------------


def test_happy_path_writes_every_field_with_a_source(tmp_path):
    out = tmp_path / "overlay.lock.json"
    assert run(Stub(), out) == 0
    lock = json.loads(out.read_text())
    assert sorted(lock) == ["bazel_sdk", "cargo_lock_sha256", "clang", "fidlgen_rust_next", "fuchsia_revision",
                            "go", "integration_revision", "product_bundle", "rules_fuchsia", "rust_host",
                            "rust_host_std", "rust_target", "sdk_version"]
    for field, entry in lock.items():
        assert entry["value"], field
        assert entry["source"] and all(isinstance(s, str) and s for s in entry["source"]), field
    assert lock["sdk_version"] == {"value": V, "source": [PB_URL]}
    assert lock["fuchsia_revision"] == {"value": FX, "source": sorted(sm_url(b) for b in BUILDS)}
    assert lock["integration_revision"]["value"] == INTEG
    assert lock["integration_revision"]["source"][-1] == (
        f"https://chrome-infra-packages.appspot.com/p/fuchsia/sdk/core/linux-amd64/+/version:{V}")
    assert lock["rust_host"] == {
        "package": "fuchsia/third_party/rust/host/linux-amd64",
        "value": HOST_ID,
        "source": [f"https://fuchsia.googlesource.com/fuchsia {FX}:manifests/toolchain",
                   f"https://chrome-infra-packages.appspot.com/p/fuchsia/third_party/rust/host/linux-amd64/+/{RUST_PIN}"],
    }
    assert lock["rust_target"]["package"] == "fuchsia/third_party/rust/target/fuchsia"
    assert lock["rust_target"]["value"] == TARGET_ID
    assert lock["rust_host_std"] == {
        "package": "fuchsia/third_party/rust/target/x86_64-unknown-linux-gnu",
        "value": HOST_STD_ID,
        "source": [f"https://fuchsia.googlesource.com/fuchsia {FX}:manifests/toolchain",
                   "https://chrome-infra-packages.appspot.com/p/fuchsia/third_party/rust/target/"
                   f"x86_64-unknown-linux-gnu/+/{RUST_PIN}"],
    }
    assert lock["clang"] == {
        "package": "fuchsia/third_party/clang/linux-amd64",
        "value": CLANG_ID,
        "source": [f"https://fuchsia.googlesource.com/fuchsia {FX}:manifests/toolchain",
                   f"https://chrome-infra-packages.appspot.com/p/fuchsia/third_party/clang/linux-amd64/+/{CLANG_PIN}"],
    }
    assert lock["go"] == {
        "package": "fuchsia/go/linux-amd64",
        "value": GO_ID,
        "source": [f"https://fuchsia.googlesource.com/fuchsia {FX}:manifests/toolchain",
                   f"https://chrome-infra-packages.appspot.com/p/fuchsia/go/linux-amd64/+/{GO_PIN}"],
    }
    assert lock["fidlgen_rust_next"] == {
        "build_id": FIDLGEN_ID,
        "url": FIDLGEN_URL,
        "value": hashlib.sha256(FIDLGEN_BYTES).hexdigest(),
        # core.vim3's build-ids.json does not name the label, so it is not a source.
        "source": [PB_URL, bid_url(BUILDS[2]), bid_url(BUILDS[1]), FIDLGEN_URL],
    }
    assert lock["bazel_sdk"] == {"url": IDK_URL, "value": hashlib.sha256(IDK_BYTES).hexdigest(), "source": [IDK_URL]}
    assert lock["rules_fuchsia"] == {
        "package": "fuchsia/development/rules_fuchsia",
        "value": RULES_ID,
        "source": [f"https://chrome-infra-packages.appspot.com/p/fuchsia/development/rules_fuchsia/+/git_revision:{INTEG}"],
    }
    assert lock["product_bundle"] == {
        "product": "core.x64",
        "url": TRANSFER_GS,
        "files": 4,
        "value": expected_bundle_digest(),
        "source": [PB_URL, TRANSFER_URL],
    }
    assert lock["cargo_lock_sha256"] == {
        "value": hashlib.sha256(CARGO_LOCK).hexdigest(),
        "source": [f"https://fuchsia.googlesource.com/fuchsia {FX}:third_party/rust_crates/Cargo.lock"],
    }


def test_output_is_sorted_indented_json_with_trailing_newline(tmp_path):
    out = tmp_path / "lock.json"
    assert run(Stub(), out) == 0
    data = out.read_bytes()
    assert data.endswith(b"}\n") and not data.endswith(b"\n\n")
    assert data == (json.dumps(json.loads(data), indent=2, sort_keys=True) + "\n").encode()


def test_git_is_read_at_the_resolved_revision_only(tmp_path):
    stub = Stub()
    assert run(stub, tmp_path / "lock.json") == 0
    git_calls = [c for c in stub.calls if c[0] == "git"]
    assert git_calls == [
        ("git", "https://fuchsia.googlesource.com/fuchsia", FX, "manifests/toolchain"),
        ("git", "https://fuchsia.googlesource.com/fuchsia", FX, "third_party/rust_crates/Cargo.lock"),
    ]


def test_no_request_goes_to_gitiles_or_carries_credentials(tmp_path):
    stub = Stub()
    assert run(stub, tmp_path / "lock.json") == 0
    urls = [c[1] for c in stub.calls]
    assert all(u.startswith("https://") for u in urls)
    assert not any("/+/" in u or "/+log" in u for u in urls if "googlesource" in u)
    assert not any("@" in u.split("//", 1)[1].split("/", 1)[0] for u in urls)


# --- determinism ------------------------------------------------------------------


def test_same_stubs_give_same_bytes(tmp_path):
    a, b = tmp_path / "a.json", tmp_path / "b.json"
    assert run(Stub(), a) == 0 and run(Stub(), b) == 0
    assert a.read_bytes() == b.read_bytes()


def test_product_bundle_order_does_not_change_output(tmp_path):
    a, b = tmp_path / "a.json", tmp_path / "b.json"
    assert run(Stub(), a) == 0
    stub = Stub()
    stub.gets[PB_URL] = list(reversed(stub.gets[PB_URL]))
    assert run(stub, b) == 0
    assert a.read_bytes() == b.read_bytes()


def test_rerun_over_existing_lock_is_byte_identical(tmp_path):
    out = tmp_path / "lock.json"
    assert run(Stub(), out) == 0
    first = out.read_bytes()
    assert run(Stub(), out) == 0
    assert out.read_bytes() == first


# --- failure paths: each exits non-zero, names the field, and leaves the lock alone ---

FAILURES = {
    "unknown version (product_bundles.json 404)":
        ("sdk_version", lambda s: s.gets.pop(PB_URL)),
    "empty product bundle list":
        ("sdk_version", lambda s: s.gets.__setitem__(PB_URL, [])),
    "bundle for another version":
        ("sdk_version", lambda s: s.gets[PB_URL][1].__setitem__("product_version", "33.20260927.3.1")),
    "bundle without a build id":
        ("sdk_version", lambda s: s.gets[PB_URL][0].__setitem__("transfer_manifest_url", "gs://x/y.json")),
    "source manifest 404":
        ("fuchsia_revision", lambda s: s.gets.pop(sm_url(BUILDS[1]))),
    "source manifest malformed":
        ("fuchsia_revision", lambda s: s.gets.__setitem__(sm_url(BUILDS[1]), {"directories": {}})),
    "source manifest not JSON":
        ("fuchsia_revision", lambda s: s.gets.__setitem__(sm_url(BUILDS[1]), b"<html>")),
    "builds disagree on fuchsia.git":
        ("fuchsia_revision", lambda s: s.gets.__setitem__(sm_url(BUILDS[2]), source_manifest(fx="0" * 40))),
    "'.' is not fuchsia.git":
        ("fuchsia_revision", lambda s: s.gets[sm_url(BUILDS[0])]["directories"]["."]["git_checkout"]
         .__setitem__("repo_url", "https://example.invalid/other")),
    "builds disagree on integration":
        ("integration_revision", lambda s: s.gets.__setitem__(sm_url(BUILDS[2]), source_manifest(integ="1" * 40))),
    "IDK not in CIPD":
        ("integration_revision", lambda s: s.cipd.pop(("fuchsia/sdk/core/linux-amd64", f"version:{V}"))),
    "IDK tag is another integration commit":
        ("integration_revision", lambda s: s.tags.__setitem__(
            ("fuchsia/sdk/core/linux-amd64", IDK_CIPD_ID), [{"key": "git_revision", "value": "2" * 40}])),
    "IDK has no git_revision tag":
        ("integration_revision", lambda s: s.tags.__setitem__(("fuchsia/sdk/core/linux-amd64", IDK_CIPD_ID), [])),
    "git fetch fails":
        ("rust_host", lambda s: setattr(s, "git_error", "git fetch: fatal: remote error")),
    "manifests/toolchain missing":
        ("rust_host", lambda s: s.git.pop("manifests/toolchain")),
    "manifests/toolchain not XML":
        ("rust_host", lambda s: s.git.__setitem__("manifests/toolchain", b"<manifest")),
    "host package not pinned":
        ("rust_host", lambda s: s.git.__setitem__("manifests/toolchain", TOOLCHAIN_XML.replace(
            b"rust/host/${platform}", b"rust/hostx/${platform}"))),
    "host package not for linux-amd64":
        ("rust_host", lambda s: s.git.__setitem__("manifests/toolchain", TOOLCHAIN_XML.replace(
            b'platforms="linux-amd64,linux-arm64,mac-amd64,mac-arm64,windows-amd64"', b'platforms="mac-arm64"'))),
    "target package not pinned":
        ("rust_target", lambda s: s.git.__setitem__("manifests/toolchain", TOOLCHAIN_XML.replace(
            b"rust/target/fuchsia\"", b"rust/target/fuchsiax\""))),
    "host std package not pinned":
        ("rust_host_std", lambda s: s.git.__setitem__("manifests/toolchain", TOOLCHAIN_XML.replace(
            b"target/x86_64-unknown-linux-gnu", b"target/x86_64-unknown-linux-musl"))),
    "host std pinned at another compiler build":
        ("rust_host_std", lambda s: s.git.__setitem__("manifests/toolchain", TOOLCHAIN_XML.replace(
            b'target/x86_64-unknown-linux-gnu"\n             version="git_revisions:c26ce708',
            b'target/x86_64-unknown-linux-gnu"\n             version="git_revisions:00000000'))),
    "target pinned at another compiler build":
        ("rust_target", lambda s: s.git.__setitem__("manifests/toolchain", TOOLCHAIN_XML.replace(
            b'target/fuchsia"\n             version="git_revisions:c26ce708',
            b'target/fuchsia"\n             version="git_revisions:00000000'))),
    "clang package not pinned":
        ("clang", lambda s: s.git.__setitem__("manifests/toolchain", TOOLCHAIN_XML.replace(
            b"clang/${platform}", b"clangx/${platform}"))),
    "clang not for linux-amd64":
        ("clang", lambda s: s.git.__setitem__("manifests/toolchain", TOOLCHAIN_XML.replace(
            b'platforms="linux-amd64,linux-arm64,mac-amd64,mac-arm64,windows-amd64"\n'
            b'             path="prebuilt/third_party/clang', b'platforms="mac-arm64"\n'
            b'             path="prebuilt/third_party/clang'))),
    "host std CIPD 404":
        ("rust_host_std", lambda s: s.cipd.pop(("fuchsia/third_party/rust/target/x86_64-unknown-linux-gnu", RUST_PIN))),
    "clang CIPD 404":
        ("clang", lambda s: s.cipd.pop(("fuchsia/third_party/clang/linux-amd64", CLANG_PIN))),
    "host CIPD 404":
        ("rust_host", lambda s: s.cipd.pop(("fuchsia/third_party/rust/host/linux-amd64", RUST_PIN))),
    "target CIPD 404":
        ("rust_target", lambda s: s.cipd.pop(("fuchsia/third_party/rust/target/fuchsia", RUST_PIN))),
    "target CIPD ambiguous tag (HTTP 400)":
        ("rust_target", lambda s: s.cipd.__setitem__(("fuchsia/third_party/rust/target/fuchsia", RUST_PIN), 400)),
    "host CIPD reply is not a SHA-256 instance":
        ("rust_host", lambda s: s.cipd.__setitem__(("fuchsia/third_party/rust/host/linux-amd64", RUST_PIN), "abc")),
    "Cargo.lock missing":
        ("cargo_lock_sha256", lambda s: s.git.pop("third_party/rust_crates/Cargo.lock")),
    "Cargo.lock empty":
        ("cargo_lock_sha256", lambda s: s.git.__setitem__("third_party/rust_crates/Cargo.lock", b"")),
    "product_bundles.json is an object":
        ("sdk_version", lambda s: s.gets.__setitem__(PB_URL, {"bundles": []})),
    "product bundle entry is a string":
        ("sdk_version", lambda s: s.gets[PB_URL].__setitem__(0, "core.x64")),
    "source manifest git_checkout is a string":
        ("fuchsia_revision", lambda s: s.gets[sm_url(BUILDS[0])]["directories"]["."].__setitem__("git_checkout", "x")),
    "source manifest revision is a number":
        ("fuchsia_revision", lambda s: [s.gets.__setitem__(sm_url(b), source_manifest(fx=7)) for b in BUILDS]),
    "IDK metadata is a list":
        ("bazel_sdk", lambda s: s.gets.__setitem__(IDK_META_URL, [1, 2])),
    "IDK download fails mid-stream":
        ("bazel_sdk", lambda s: s.digests.__setitem__(IDK_URL, rp.FetchError("GET x: IncompleteRead: 5 bytes read"))),
    "IDK metadata 404":
        ("bazel_sdk", lambda s: s.gets.pop(IDK_META_URL)),
    "IDK metadata lacks md5":
        ("bazel_sdk", lambda s: s.gets.__setitem__(IDK_META_URL, {"size": "3"})),
    "IDK download 404":
        ("bazel_sdk", lambda s: s.digests.pop(IDK_URL)),
    "IDK download truncated":
        ("bazel_sdk", lambda s: s.digests.__setitem__(IDK_URL, IDK_BYTES[:-1])),
    "IDK download corrupted":
        ("bazel_sdk", lambda s: s.digests.__setitem__(IDK_URL, IDK_BYTES.upper())),
    "host CIPD reply is a list":
        ("rust_host", lambda s: s.cipd.__setitem__(("fuchsia/third_party/rust/host/linux-amd64", RUST_PIN), b"[]")),
    "host CIPD instance is a string":
        ("rust_host", lambda s: s.cipd.__setitem__(("fuchsia/third_party/rust/host/linux-amd64", RUST_PIN),
                                                  b'{"instance": "abc"}')),
    "IDK CIPD tags is an object":
        ("integration_revision", lambda s: s.tags.__setitem__(("fuchsia/sdk/core/linux-amd64", IDK_CIPD_ID),
                                                             b'{"tags": {"git_revision": "x"}}')),
    "IDK CIPD tag entry is a string":
        ("integration_revision", lambda s: s.tags.__setitem__(("fuchsia/sdk/core/linux-amd64", IDK_CIPD_ID),
                                                             b'{"tags": ["git_revision:x"]}')),
    "rules_fuchsia 404 at integration revision":
        ("rules_fuchsia", lambda s: s.cipd.pop(("fuchsia/development/rules_fuchsia", f"git_revision:{INTEG}"))),
    "rules_fuchsia version tag names another instance":
        ("rules_fuchsia", lambda s: s.cipd.__setitem__(("fuchsia/development/rules_fuchsia", f"version:{V}"), "e" * 64)),
    "no core.x64 bundle":
        ("product_bundle", lambda s: s.gets[PB_URL].pop(1)),
    "core.x64 transfer URL is not gs://":
        ("product_bundle", lambda s: s.gets[PB_URL][1].__setitem__(
            "transfer_manifest_url", f"https://example.invalid/builds/{BUILDS[1]}/transfer.json")),
    "transfer manifest 404":
        ("product_bundle", lambda s: s.gets.pop(TRANSFER_URL)),
    "transfer manifest not JSON":
        ("product_bundle", lambda s: s.gets.__setitem__(TRANSFER_URL, b"<html>")),
    "transfer manifest version 2":
        ("product_bundle", lambda s: s.gets[TRANSFER_URL].__setitem__("version", "2")),
    "transfer manifest has no entries":
        ("product_bundle", lambda s: s.gets[TRANSFER_URL].__setitem__("entries", [])),
    "transfer entry of unknown type":
        ("product_bundle", lambda s: s.gets[TRANSFER_URL]["entries"][0].__setitem__("type", "links")),
    "transfer entry local outside the bundle":
        ("product_bundle", lambda s: s.gets[TRANSFER_URL]["entries"][1].__setitem__("local", "elsewhere")),
    "transfer file name escapes the bundle":
        ("product_bundle", lambda s: s.gets[TRANSFER_URL]["entries"][1]["entries"].append({"name": "../x"})),
    "transfer file name is absolute":
        ("product_bundle", lambda s: s.gets[TRANSFER_URL]["entries"][1]["entries"].append({"name": "/etc/x"})),
    "transfer file listed twice":
        ("product_bundle", lambda s: s.gets[TRANSFER_URL]["entries"][0]["entries"].append({"name": BLOB_A})),
    "bundle blob 404":
        ("product_bundle", lambda s: s.digests.pop(BUNDLE_FILES[f"blobs/1/{BLOB_B}"][0])),
    "bundle file download fails mid-stream":
        ("product_bundle", lambda s: s.digests.__setitem__(BUNDLE_FILES["system_a/fuchsia.zbi"][0],
                                                          rp.FetchError("GET x: IncompleteRead: 1 bytes read"))),
    "go package not pinned":
        ("go", lambda s: s.git.__setitem__("manifests/toolchain", TOOLCHAIN_XML.replace(
            b"fuchsia/go/${platform}", b"fuchsia/golang/${platform}"))),
    "go not for linux-amd64":
        ("go", lambda s: s.git.__setitem__("manifests/toolchain", TOOLCHAIN_XML.replace(
            b'platforms="linux-amd64,linux-arm64"\n             path="prebuilt/third_party/go',
            b'platforms="linux-arm64"\n             path="prebuilt/third_party/go'))),
    "go CIPD 404":
        ("go", lambda s: s.cipd.pop(("fuchsia/go/linux-amd64", GO_PIN))),
    "core.x64 build-ids.json 404":
        ("fidlgen_rust_next", lambda s: s.gets.pop(bid_url(BUILDS[1]))),
    "another build's build-ids.json 404":
        ("fidlgen_rust_next", lambda s: s.gets.pop(bid_url(BUILDS[0]))),
    "build-ids.json not JSON":
        ("fidlgen_rust_next", lambda s: s.gets.__setitem__(bid_url(BUILDS[2]), b"<html>")),
    "build-ids.json is a list":
        ("fidlgen_rust_next", lambda s: s.gets.__setitem__(bid_url(BUILDS[2]), [FIDLGEN_ID])),
    "core.x64 does not name the generator":
        ("fidlgen_rust_next", lambda s: s.gets.__setitem__(bid_url(BUILDS[1]), {FIDLGEN_ID: FIDLGEN_NOVARIANT})),
    "builds disagree on the generator's build ID":
        ("fidlgen_rust_next", lambda s: s.gets.__setitem__(bid_url(BUILDS[2]), {"3" * 40: FIDLGEN_LABEL})),
    "one build names two build IDs for the generator":
        ("fidlgen_rust_next", lambda s: s.gets[bid_url(BUILDS[1])].__setitem__("3" * 40, FIDLGEN_LABEL)),
    "generator build ID is not hex":
        ("fidlgen_rust_next", lambda s: [s.gets.__setitem__(bid_url(b), {"../x": FIDLGEN_LABEL}) for b in BUILDS[1:]]),
    "generator executable 404":
        ("fidlgen_rust_next", lambda s: s.gets.pop(FIDLGEN_URL)),
    "generator executable is not ELF":
        ("fidlgen_rust_next", lambda s: s.gets.__setitem__(FIDLGEN_URL, b"<html>" + bytes(100))),
    "generator executable is ELF32":
        ("fidlgen_rust_next", lambda s: s.gets.__setitem__(FIDLGEN_URL, make_elf(elf_class=1))),
    "generator executable is for arm64":
        ("fidlgen_rust_next", lambda s: s.gets.__setitem__(FIDLGEN_URL, make_elf(machine=183))),
    "generator executable has no build ID note":
        ("fidlgen_rust_next", lambda s: s.gets.__setitem__(FIDLGEN_URL, make_elf(build_ids=()))),
    "generator note has another type":
        ("fidlgen_rust_next", lambda s: s.gets.__setitem__(FIDLGEN_URL, make_elf(note_type=1))),
    "generator note has another owner":
        ("fidlgen_rust_next", lambda s: s.gets.__setitem__(FIDLGEN_URL, make_elf(note_name=b"LLVM\0"))),
    "generator executable has another build ID":
        ("fidlgen_rust_next", lambda s: s.gets.__setitem__(FIDLGEN_URL, make_elf(build_ids=("4" * 40,)))),
    "generator executable has two build IDs":
        ("fidlgen_rust_next", lambda s: s.gets.__setitem__(FIDLGEN_URL, make_elf(build_ids=(FIDLGEN_ID, "4" * 40)))),
    "generator note runs past the end of the file":
        ("fidlgen_rust_next", lambda s: s.gets.__setitem__(FIDLGEN_URL, make_elf(truncate_note=True))),
    "generator executable truncated":
        ("fidlgen_rust_next", lambda s: s.gets.__setitem__(FIDLGEN_URL, FIDLGEN_BYTES[:100])),
    "rules_fuchsia version lookup fails other than 404":
        ("rules_fuchsia", lambda s: s.cipd.__setitem__(("fuchsia/development/rules_fuchsia", f"version:{V}"), 500)),
}


@pytest.mark.parametrize("case", sorted(FAILURES))
def test_failure_names_field_and_leaves_lock_unchanged(case, tmp_path, capsys):
    field, breaker = FAILURES[case]
    out = tmp_path / "overlay.lock.json"
    out.write_bytes(b"previous lock\n")
    before = os.stat(out)
    stub = Stub()
    breaker(stub)
    assert run(stub, out) != 0
    err = capsys.readouterr().err
    assert f"error: {field}: " in err, err
    assert "left unchanged" in err
    assert out.read_bytes() == b"previous lock\n"
    assert os.stat(out).st_ino == before.st_ino
    assert sorted(p.name for p in tmp_path.iterdir()) == ["overlay.lock.json"]


def test_failure_without_existing_lock_creates_nothing(tmp_path):
    stub = Stub()
    stub.gets.pop(PB_URL)
    assert run(stub, tmp_path / "lock.json") != 0
    assert list(tmp_path.iterdir()) == []


@pytest.mark.parametrize("bad", ["", "latest", "33.x.1", "../33.1", "33.20260927.4.1/"])
def test_malformed_version_rejected_before_any_request(bad, tmp_path, capsys):
    stub = Stub()
    assert run(stub, tmp_path / "lock.json", version=bad) != 0
    assert "error: sdk_version: " in capsys.readouterr().err
    assert stub.calls == []


def test_rules_fuchsia_without_version_tag_is_accepted(tmp_path):
    stub = Stub()
    stub.cipd.pop(("fuchsia/development/rules_fuchsia", f"version:{V}"))
    out = tmp_path / "lock.json"
    assert run(stub, out) == 0
    assert json.loads(out.read_text())["rules_fuchsia"]["value"] == RULES_ID


# --- atomic write ------------------------------------------------------------------


def test_failure_between_temp_write_and_replace_keeps_old_lock(tmp_path, monkeypatch):
    out = tmp_path / "overlay.lock.json"
    out.write_bytes(b"previous lock\n")

    def boom(src, dst):
        assert Path(src).read_bytes().startswith(b"{")  # the temp file was fully written
        raise OSError("simulated crash before rename")

    monkeypatch.setattr(rp.os, "replace", boom)
    with pytest.raises(OSError, match="simulated"):
        run(Stub(), out)
    assert out.read_bytes() == b"previous lock\n"
    assert [p.name for p in tmp_path.iterdir()] == ["overlay.lock.json"]


def test_failure_while_writing_temp_keeps_old_lock(tmp_path, monkeypatch):
    out = tmp_path / "overlay.lock.json"
    out.write_bytes(b"previous lock\n")
    monkeypatch.setattr(rp.os, "fsync", lambda fd: (_ for _ in ()).throw(OSError("disk full")))
    with pytest.raises(OSError, match="disk full"):
        rp.write_atomically(out, b"new")
    assert out.read_bytes() == b"previous lock\n"
    assert [p.name for p in tmp_path.iterdir()] == ["overlay.lock.json"]


# --- the live git path, against a local repository (no network) -------------------


def _git(*args, cwd):
    return subprocess.run(["git", *args], cwd=cwd, check=True, capture_output=True).stdout.decode().strip()


@pytest.fixture
def local_repo(tmp_path):
    """A two-commit repository served over file://; returns (url, first commit)."""
    src = tmp_path / "src"
    (src / "manifests").mkdir(parents=True)
    _git("init", "-q", cwd=src)
    _git("config", "uploadpack.allowFilter", "true", cwd=src)
    _git("config", "uploadpack.allowAnySHA1InWant", "true", cwd=src)
    (src / "manifests" / "toolchain").write_bytes(b"old\n")
    _git("add", ".", cwd=src)
    commit = ["-c", "user.name=t", "-c", "user.email=t@example.invalid", "-c", "commit.gpgsign=false", "commit", "-q"]
    _git(*commit, "-m", "one", cwd=src)
    first = _git("rev-parse", "HEAD", cwd=src)
    (src / "manifests" / "toolchain").write_bytes(TOOLCHAIN_XML)
    _git(*commit, "-am", "two", cwd=src)
    return src.as_uri(), first


def test_live_git_show_reads_files_at_a_commit(local_repo):
    url, first = local_repo
    up = rp.LiveUpstream()
    try:
        assert up.git_show(url, first, "manifests/toolchain") == b"old\n"
        with pytest.raises(rp.FetchError, match="cat-file"):
            up.git_show(url, first, "no/such/file")
        with pytest.raises(rp.FetchError, match="fetch"):
            up.git_show(url, "0" * 40, "manifests/toolchain")
    finally:
        up.close()


def test_live_git_ignores_user_and_env_git_config(local_repo, tmp_path, monkeypatch):
    """C1: config from HOME, XDG, GIT_CONFIG_* and ~/.netrc must not reach the fetch.

    The hostile config rewrites the repository URL to a path that does not exist, sets a
    cookie file and an extra header, and a ~/.netrc holds a password. The control run
    shows plain git obeys it; the resolver's git must not.
    """
    url, first = local_repo
    home = tmp_path / "hostile-home"
    (home / "git").mkdir(parents=True)
    bogus = (tmp_path / "does-not-exist").as_uri()
    hostile = (f'[url "{bogus}"]\n\tinsteadOf = {url}\n'
               f"[http]\n\tcookiefile = {home}/cookies\n\textraHeader = Authorization: Bearer leaked\n")
    (home / ".gitconfig").write_text(hostile)
    (home / "git" / "config").write_text(hostile)
    (home / "cookies").write_text(".googlesource.com\tTRUE\t/\tTRUE\t2147483647\to\tgit-x=leaked\n")
    (home / ".netrc").write_text("machine fuchsia.googlesource.com login x password leaked\n")
    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setenv("XDG_CONFIG_HOME", str(home))
    monkeypatch.delenv("GIT_CONFIG_GLOBAL", raising=False)
    monkeypatch.delenv("GIT_CONFIG_NOSYSTEM", raising=False)
    monkeypatch.setenv("GIT_CONFIG_COUNT", "1")
    monkeypatch.setenv("GIT_CONFIG_KEY_0", f"url.{bogus}.insteadOf")
    monkeypatch.setenv("GIT_CONFIG_VALUE_0", url)
    monkeypatch.setenv("GIT_CONFIG_PARAMETERS", f"'url.{bogus}.insteadof'='{url}'")

    # Control: plain git under this environment is redirected and fails.
    probe = tmp_path / "probe.git"
    subprocess.run(["git", "init", "-q", "--bare", str(probe)], check=True, capture_output=True)
    control = subprocess.run(["git", "-C", str(probe), "fetch", "-q", "--depth", "1", url, first],
                             capture_output=True)
    assert control.returncode != 0 and b"does-not-exist" in control.stderr

    up = rp.LiveUpstream()
    try:
        assert up.git_show(url, first, "manifests/toolchain") == b"old\n"
    finally:
        up.close()


def _serve_once(handler_body):
    """Serve one HTTP response on 127.0.0.1 from a thread; returns the URL."""
    import http.server
    import threading

    class Handler(http.server.BaseHTTPRequestHandler):
        def do_GET(self):  # noqa: N802
            handler_body(self)

        def log_message(self, *args):
            pass

    server = http.server.HTTPServer(("127.0.0.1", 0), Handler)
    threading.Thread(target=server.handle_request, daemon=True).start()
    return f"http://127.0.0.1:{server.server_port}/core.tar.gz"


def _truncated(h):
    h.send_response(200)
    h.send_header("Content-Length", "1000")
    h.end_headers()
    h.wfile.write(b"only a little")
    h.wfile.flush()
    h.close_connection = True


def test_live_digest_truncated_body_is_a_fetch_error(monkeypatch):
    monkeypatch.setenv("no_proxy", "127.0.0.1")
    with pytest.raises(rp.FetchError, match="IncompleteRead"):
        rp.LiveUpstream().digest(_serve_once(_truncated))


def test_live_get_truncated_body_is_a_fetch_error(monkeypatch):
    monkeypatch.setenv("no_proxy", "127.0.0.1")
    with pytest.raises(rp.FetchError, match="IncompleteRead"):
        rp.LiveUpstream().get(_serve_once(_truncated))


def test_truncated_idk_stream_names_bazel_sdk(tmp_path, capsys):
    stub = Stub()
    live = rp.LiveUpstream()
    stub.digest = lambda url: live.digest(_serve_once(_truncated))
    out = tmp_path / "lock.json"
    assert run(stub, out) != 0
    assert "error: bazel_sdk: " in capsys.readouterr().err
    assert not out.exists()


# --- file mode -------------------------------------------------------------------------


def test_new_lock_is_world_readable(tmp_path):
    out = tmp_path / "lock.json"
    old = os.umask(0o022)
    try:
        assert run(Stub(), out) == 0
    finally:
        os.umask(old)
    assert os.stat(out).st_mode & 0o777 == 0o644


def test_rewritten_lock_keeps_existing_mode(tmp_path):
    out = tmp_path / "lock.json"
    out.write_bytes(b"old\n")
    os.chmod(out, 0o664)
    assert run(Stub(), out) == 0
    assert os.stat(out).st_mode & 0o777 == 0o664


def test_parse_toolchain_manifest_reads_every_pin():
    assert rp.parse_toolchain_manifest(TOOLCHAIN_XML) == {
        "rust_host": RUST_PIN, "rust_target": RUST_PIN, "rust_host_std": RUST_PIN, "clang": CLANG_PIN,
        "go": GO_PIN}


def test_elf_build_ids_reads_the_gnu_note():
    assert rp.elf_build_ids("f", make_elf(), "x") == {FIDLGEN_ID}
    assert rp.elf_build_ids("f", make_elf(build_ids=()), "x") == set()


def test_fidlgen_rust_next_changes_when_the_executable_changes(tmp_path):
    a, b = tmp_path / "a.json", tmp_path / "b.json"
    assert run(Stub(), a) == 0
    stub = Stub()
    stub.gets[FIDLGEN_URL] = FIDLGEN_BYTES + b"\0"  # same build ID note, other bytes
    assert run(stub, b) == 0
    assert (json.loads(a.read_text())["fidlgen_rust_next"]["value"]
            != json.loads(b.read_text())["fidlgen_rust_next"]["value"])


def test_fidlgen_rust_next_needs_exactly_one_core_x64_build():
    # resolve() checks core.x64 first (product_bundle); the generator's own check still holds.
    for names in (["core.vim3", "core.x64-other", "minimal.arm64"], ["core.x64", "core.x64", "minimal.arm64"]):
        stub = Stub()
        for entry, name in zip(stub.gets[PB_URL], names):
            entry["name"] = name
        with pytest.raises(rp.ResolveError, match="builds named core.x64") as e:
            rp.resolve_fidlgen_rust_next(stub, V)
        assert e.value.field == "fidlgen_rust_next"


def test_fidlgen_rust_next_refuses_two_bundles_of_one_build():
    stub = Stub()
    stub.gets[PB_URL][2]["transfer_manifest_url"] = stub.gets[PB_URL][1]["transfer_manifest_url"]
    with pytest.raises(rp.ResolveError, match=f"minimal.arm64 and core.x64 name the same build {BUILDS[1]}") as e:
        rp.resolve_fidlgen_rust_next(stub, V)
    assert e.value.field == "fidlgen_rust_next"


def test_fidlgen_rust_next_only_in_core_x64_is_accepted(tmp_path):
    stub = Stub()
    stub.gets[bid_url(BUILDS[2])] = {}
    out = tmp_path / "lock.json"
    assert run(stub, out) == 0
    assert json.loads(out.read_text())["fidlgen_rust_next"]["source"] == [PB_URL, bid_url(BUILDS[1]), FIDLGEN_URL]


def test_cipd_xssi_prefix_is_stripped():
    stub = Stub()
    assert rp.cipd_resolve(stub, "rust_host", "fuchsia/third_party/rust/host/linux-amd64", RUST_PIN) == HOST_ID


def test_bundle_digest_definition():
    # SHA-256 over sorted "<path>\t<sha256>\n" lines; order of the input does not matter.
    files = {"b": "2" * 64, "a/x": "1" * 64}
    lines = f"a/x\t{'1' * 64}\nb\t{'2' * 64}\n"
    assert rp.bundle_digest(files) == hashlib.sha256(lines.encode()).hexdigest()
    assert rp.bundle_digest(dict(reversed(list(files.items())))) == rp.bundle_digest(files)
    assert rp.bundle_digest({**files, "c": "3" * 64}) != rp.bundle_digest(files)


def test_parse_transfer_manifest_maps_bundle_paths_to_urls():
    files = rp.parse_transfer_manifest("product_bundle", json.dumps(transfer_manifest()).encode(), TRANSFER_URL)
    assert files == {path: url for path, (url, _) in BUNDLE_FILES.items()}


def test_product_bundle_changes_when_a_file_changes(tmp_path):
    a, b = tmp_path / "a.json", tmp_path / "b.json"
    assert run(Stub(), a) == 0
    stub = Stub()
    stub.digests[BUNDLE_FILES["system_a/fuchsia.zbi"][0]] = b"another zbi"
    assert run(stub, b) == 0
    assert json.loads(a.read_text())["product_bundle"]["value"] != json.loads(b.read_text())["product_bundle"]["value"]
