#!/bin/sh
# SPDX-FileCopyrightText: 2026 Curtis Galloway
# SPDX-License-Identifier: Apache-2.0
# The emulator harness (scripts/emu.py). Needs python3 >= 3.11 on PATH, as the IDK fetch does.
exec python3 "$(dirname "$0")/emu.py" "$@"
