#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Curtis Galloway
# SPDX-License-Identifier: Apache-2.0
"""Regenerate the overlay's copies of upstream code (design R6, D6, D9; milestone M5).

Usage:
  regen.py vendor     rewrite vendor/fuchsia/ and third_party/crates/ from upstream
  regen.py --check    regenerate into a scratch directory and report drift (exit 1)

Only the vendor stage exists so far; the full pipeline (R1 -> R4 -> R5 -> R6, the
closure report, builds) is milestone M14.

Inputs, all committed:
  overlay.lock.json        fuchsia_revision (what to copy) and cargo_lock_sha256
  vendor/crates.txt        one "<upstream path> <upstream|overlay>" per line: which
                           fuchsia.git directories to copy, and where each one's
                           BUILD.bazel comes from (upstream's, rewritten, or ours)
  overlays/<path>/BUILD.bazel     hand-written BUILD file for an "overlay" crate
  patches/fuchsia/<path>/*.patch  applied in name order after the BUILD files

Outputs, generated and committed (D6); never edit them by hand:
  vendor/fuchsia/<path>/   each listed directory, byte-for-byte from fuchsia.git at the
                           revision, except BUILD.bazel and what patches change (D9).
                           Subdirectories that are packages of their own (a BUILD.bazel
                           or BUILD.gn) are left out; list them separately.
  vendor/fuchsia/LICENSE, PATENTS   fuchsia.git's root files, which cover every file
                           under vendor/fuchsia/ as they cover the upstream tree (C4)
  vendor/fuchsia/BUILD.bazel        the license target upstream BUILD files name as
                           //:license
  third_party/crates/      the crates.io crates the vendored BUILD files depend on:
                           upstream's crate_universe-generated BUILD files
                           (fuchsia.git third_party/rust_crates/vendor/<crate>/BUILD.bazel)
                           with labels rewritten, and crates.json, which lists each
                           crate's static.crates.io URL and the SHA-256 the release's
                           Cargo.lock gives it. //toolchain:crates.bzl turns this into
                           the @rust_crates repository; the build downloads each crate
                           by that checksum and resolves nothing.

Label rewriting for upstream BUILD.bazel files (strings only, comments untouched):
  //build/bazel/rules/rust:defs.bzl        -> //rules:rustc.bzl
  //build/config/rust/lints:<x>            -> //rules/lints:<x>
  //:license                               -> //vendor/fuchsia:license
  //third_party/rust_crates/vendor:<x>     -> @rust_crates//vendor:<x>
  //<path>[:<t>], <path> listed            -> //vendor/fuchsia/<path>[:<t>]
Every rustc_library/rustc_binary/rustc_proc_macro call gets `vendored = True`: the
overlay builds upstream code at HEAD, which upstream builds at PLATFORM, so its lints
are upstream's concern (M4 review). Any other //-label fails the run and names the file,
the label and why (for example a patched crate from third_party/rust_crates/forks,
which is milestone M6).

Git access (C1): one depth-1, blobless fetch of the revision into a scratch directory,
then one fetch of exactly the blobs needed, by object ID, with git isolated from user
and system configuration (resolve_pins.isolated_git). Nothing is fetched at build time.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import stat
import sys
import tempfile
import tomllib
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Protocol

import resolve_pins
from resolve_pins import FetchError, isolated_git

ROOT = Path(__file__).resolve().parent.parent
FUCHSIA_GIT = resolve_pins.FUCHSIA_GIT

VENDOR_LIST = "vendor/crates.txt"
VENDOR_OUT = "vendor/fuchsia"
CRATES_OUT = "third_party/crates"
OVERLAYS = "overlays"
PATCHES = "patches/fuchsia"
# Every generated tree, relative to the repository root. --check compares these.
OUTPUTS = (VENDOR_OUT, CRATES_OUT)

# fuchsia.git root files copied to vendor/fuchsia/ (their license covers every file).
ROOT_FILES = ("LICENSE", "PATENTS")

RUST_CRATES = "third_party/rust_crates"
RUST_CRATES_VENDOR = f"{RUST_CRATES}/vendor"
CARGO_LOCK = f"{RUST_CRATES}/Cargo.lock"
CRATES_IO_SOURCE = "registry+https://github.com/rust-lang/crates.io-index"
CRATE_URL = "https://static.crates.io/crates/{name}/{name}-{version}.crate"
CRATES_REPO = "rust_crates"

RUSTC_MACROS = ("rustc_library", "rustc_binary", "rustc_proc_macro")
PACKAGE_FILES = ("BUILD.bazel", "BUILD.gn")

# Labels that are Bazel built-ins, not packages.
_BUILTIN_PREFIXES = ("//visibility:", "//conditions:")

GENERATED_BY = "Generated by scripts/regen.py"


class RegenError(Exception):
    """The run cannot produce a correct tree; the message names the input at fault."""


# --- upstream access -----------------------------------------------------------


class Source(Protocol):
    """Read-only view of fuchsia.git at one revision. Tests substitute a directory."""

    revision: str

    def files(self, path: str) -> dict[str, int]:
        """Every file under `path` (repo-relative, recursive) -> its mode (0o644/0o755).

        Raises RegenError if `path` has no files, or holds a symlink or submodule.
        """
        ...

    def read(self, paths: list[str]) -> dict[str, bytes]:
        """The contents of each repo-relative file. Raises RegenError if one is missing."""
        ...


class DirSource:
    """A plain directory laid out like fuchsia.git (tests, or a local checkout)."""

    def __init__(self, root: Path, revision: str):
        self.root = root
        self.revision = revision

    def files(self, path: str) -> dict[str, int]:
        base = self.root / path
        out: dict[str, int] = {}
        if base.is_dir():
            for p in sorted(base.rglob("*")):
                if p.is_symlink():
                    raise RegenError(f"{p.relative_to(self.root).as_posix()}: symlinks are not supported")
                if p.is_file():
                    mode = 0o755 if p.stat().st_mode & stat.S_IXUSR else 0o644
                    out[p.relative_to(self.root).as_posix()] = mode
        if not out:
            raise RegenError(f"{path}: no such directory at {self.revision}")
        return out

    def read(self, paths: list[str]) -> dict[str, bytes]:
        out = {}
        for p in paths:
            f = self.root / p
            if not f.is_file():
                raise RegenError(f"{p}: no such file at {self.revision}")
            out[p] = f.read_bytes()
        return out


class GitSource:
    """fuchsia.git over anonymous HTTPS (C1): depth-1 blobless fetch, blobs by ID."""

    def __init__(self, repo: str, revision: str, workdir: Path):
        self.repo = repo
        self.revision = revision
        self.gitdir = workdir / "fuchsia.git"
        self.home = workdir / "home"
        self._fetched_blobs: set[str] = set()
        self.home.mkdir(parents=True, exist_ok=True)
        self.gitdir.mkdir(parents=True, exist_ok=True)
        self._git("init", "-q", "--bare")
        self._git("fetch", "-q", "--no-tags", "--depth", "1", "--filter=blob:none", repo, revision)
        fetched = self._git("rev-parse", "FETCH_HEAD").decode().strip()
        if fetched != revision:
            raise RegenError(f"git fetch {repo} {revision}: got {fetched}")
        self._entries: dict[str, tuple[int, str]] = {}

    def _git(self, *args: str, stdin: bytes | None = None) -> bytes:
        try:
            return isolated_git(self.gitdir, self.home, *args, stdin=stdin)
        except FetchError as e:
            raise RegenError(str(e)) from None

    def files(self, path: str) -> dict[str, int]:
        raw = self._git("ls-tree", "-r", "-z", "--full-tree", self.revision, "--", path)
        out: dict[str, int] = {}
        for rec in raw.split(b"\0"):
            if not rec:
                continue
            meta, name = rec.split(b"\t", 1)
            mode, kind, oid = meta.decode().split()
            name = name.decode()
            if name != path and not name.startswith(path + "/"):
                continue
            if kind != "blob" or mode not in ("100644", "100755"):
                raise RegenError(f"{name}: unsupported git entry (mode {mode}, {kind})")
            out[name] = 0o755 if mode == "100755" else 0o644
            self._entries[name] = (out[name], oid)
        if not out:
            raise RegenError(f"{path}: no such directory at {self.revision}")
        return out

    def _oid(self, path: str) -> str:
        if path not in self._entries:
            raw = self._git("ls-tree", "-z", "--full-tree", self.revision, "--", path)
            recs = [r for r in raw.split(b"\0") if r]
            if len(recs) != 1:
                raise RegenError(f"{path}: no such file at {self.revision}")
            meta, _ = recs[0].split(b"\t", 1)
            mode, kind, oid = meta.decode().split()
            if kind != "blob":
                raise RegenError(f"{path}: not a file at {self.revision}")
            self._entries[path] = (0o755 if mode == "100755" else 0o644, oid)
        return self._entries[path][1]

    def read(self, paths: list[str]) -> dict[str, bytes]:
        oids = {p: self._oid(p) for p in paths}
        missing = sorted(set(oids.values()) - self._fetched_blobs)
        if missing:
            # One request for every blob not yet local, as git's own partial-clone
            # prefetch does; without it cat-file would fetch them one at a time.
            self._git("-c", "fetch.negotiationAlgorithm=noop", "fetch", "-q", "--no-tags",
                      "--no-write-fetch-head", "--filter=blob:none", self.repo, *missing)
            self._fetched_blobs.update(missing)
        out: dict[str, bytes] = {}
        batch = self._git("cat-file", "--batch", stdin="".join(f"{oids[p]}\n" for p in paths).encode())
        pos = 0
        for p in paths:
            nl = batch.index(b"\n", pos)
            header = batch[pos:nl].decode().split()
            if len(header) != 3 or header[1] != "blob":
                raise RegenError(f"{p}: cat-file returned {' '.join(header)}")
            size = int(header[2])
            out[p] = batch[nl + 1:nl + 1 + size]
            pos = nl + 1 + size + 1
        return out


# --- inputs ----------------------------------------------------------------------


@dataclass(frozen=True)
class Crate:
    path: str  # upstream path, e.g. sdk/rust/zx-types
    build: str  # "upstream" or "overlay"


def _check_path(path: str, where: str) -> str:
    p = PurePosixPath(path)
    if (not path or p.is_absolute() or any(part in ("", ".", "..") for part in path.split("/"))
            or path.endswith("/")):
        raise RegenError(f"{where}: {path!r} is not a normalized relative path")
    return path


def read_vendor_list(text: str, where: str = VENDOR_LIST) -> list[Crate]:
    """Parse vendor/crates.txt: "<path> <upstream|overlay>", '#' comments."""
    crates: list[Crate] = []
    seen: set[str] = set()
    for n, line in enumerate(text.splitlines(), 1):
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        fields = line.split()
        if len(fields) != 2 or fields[1] not in ("upstream", "overlay"):
            raise RegenError(f"{where}:{n}: expected '<upstream path> upstream|overlay', got {line!r}")
        path = _check_path(fields[0], f"{where}:{n}")
        if path in seen:
            raise RegenError(f"{where}:{n}: {path} is listed twice")
        seen.add(path)
        crates.append(Crate(path, fields[1]))
    return crates


def read_lock(root: Path) -> tuple[str, str]:
    """(fuchsia_revision, cargo_lock_sha256) from overlay.lock.json."""
    lock = json.loads((root / "overlay.lock.json").read_text())
    try:
        revision = lock["fuchsia_revision"]["value"]
        cargo_sha = lock["cargo_lock_sha256"]["value"]
    except (KeyError, TypeError):
        raise RegenError("overlay.lock.json: needs fuchsia_revision and cargo_lock_sha256") from None
    if not re.fullmatch(r"[0-9a-f]{40}", revision):
        raise RegenError(f"overlay.lock.json: fuchsia_revision {revision!r} is not a commit")
    return revision, cargo_sha


# --- BUILD file rewriting ---------------------------------------------------------

# A comment, or a double-quoted string. Upstream BUILD files are buildifier-formatted,
# which writes every string with double quotes.
_TOKENS = re.compile(r'(#[^\n]*)|("(?:[^"\\\n]|\\.)*")')
_RUSTC_CALL = re.compile(r"\b(" + "|".join(RUSTC_MACROS) + r")\(")
_RUSTC_LOAD = re.compile(r'load\(\s*"//rules:rustc\.bzl"((?:\s*,\s*"[^"]*")*)\s*,?\s*\)')


def _code_spans(text: str) -> list[tuple[int, int]]:
    """Spans of `text` outside comments and strings."""
    spans, pos = [], 0
    for m in _TOKENS.finditer(text):
        spans.append((pos, m.start()))
        pos = m.end()
    spans.append((pos, len(text)))
    return spans


def _map_strings(text: str, fn) -> str:
    """Replace each string literal's contents with fn(contents); comments are kept."""
    def sub(m: re.Match) -> str:
        if m.group(1) is not None:
            return m.group(1)
        return '"' + fn(m.group(2)[1:-1]) + '"'
    return _TOKENS.sub(sub, text)


def _strings(text: str) -> list[str]:
    """The contents of every string literal outside comments."""
    return [m.group(2)[1:-1] for m in _TOKENS.finditer(text) if m.group(2) is not None]


def _split_label(label: str) -> tuple[str, str]:
    """"//a/b:c" -> ("a/b", ":c"); "//a/b" -> ("a/b", "")."""
    body = label[2:]
    pkg, colon, target = body.partition(":")
    return pkg, (colon + target) if colon else ""


def rewrite_upstream_build(text: str, where: str, vendored_paths: set[str]) -> str:
    """Rewrite an upstream in-tree BUILD.bazel for vendor/fuchsia/ (see module doc)."""

    def label(s: str) -> str:
        if not s.startswith("//") or s.startswith(_BUILTIN_PREFIXES):
            return s
        pkg, target = _split_label(s)
        if s == "//build/bazel/rules/rust:defs.bzl":
            return "//rules:rustc.bzl"
        if pkg == "build/config/rust/lints" and target:
            return "//rules/lints" + target
        if s == "//:license":
            return f"//{VENDOR_OUT}:license"
        if pkg == RUST_CRATES_VENDOR and target:
            return f"@{CRATES_REPO}//vendor" + target
        if pkg == RUST_CRATES or pkg.startswith(RUST_CRATES + "/"):
            raise RegenError(f"{where}: {s}: only crates.io crates from {RUST_CRATES_VENDOR} "
                             "are supported; patched and forked crates come in milestone M6")
        if pkg in vendored_paths:
            return f"//{VENDOR_OUT}/{pkg}{target}"
        if pkg.startswith("build/"):
            raise RegenError(f"{where}: {s}: no overlay mapping for this build label")
        raise RegenError(f"{where}: depends on {s}, but {pkg} is not listed in {VENDOR_LIST}")

    out = _map_strings(text, label)

    for m in _RUSTC_LOAD.finditer(out):
        names = re.findall(r'"([^"]*)"', m.group(1))
        unsupported = [n for n in names if n not in RUSTC_MACROS]
        if unsupported:
            raise RegenError(f"{where}: loads {', '.join(unsupported)} from //rules:rustc.bzl, "
                             f"which provides only {', '.join(RUSTC_MACROS)}")
    return add_vendored(out, where)


def add_vendored(text: str, where: str) -> str:
    """Insert `vendored = True` as the first argument of every rustc_* call."""
    spans = _code_spans(text)
    inserts: list[int] = []
    for start, end in spans:
        for m in _RUSTC_CALL.finditer(text, start, end):
            inserts.append(m.end())
    for pos in reversed(inserts):
        close = _matching_paren(text, pos - 1)
        if re.search(r"\bvendored\s*=", text[pos:close]):
            raise RegenError(f"{where}: a rustc_* call already sets vendored; remove it upstream "
                             "of regen.py (patches/fuchsia/) or use an overlay")
        line_start = text.rfind("\n", 0, pos) + 1
        indent = re.match(r"[ \t]*", text[line_start:]).group(0)
        if text[pos:pos + 1] == "\n":
            text = text[:pos] + f"\n{indent}    vendored = True,  # {GENERATED_BY}" + text[pos:]
        else:
            text = text[:pos] + "vendored = True, " + text[pos:]
    return text


def _matching_paren(text: str, open_pos: int) -> int:
    depth = 0
    for m in re.finditer(r'(#[^\n]*)|("(?:[^"\\\n]|\\.)*")|([()])', text[open_pos:]):
        if m.group(3) == "(":
            depth += 1
        elif m.group(3) == ")":
            depth -= 1
            if depth == 0:
                return open_pos + m.start()
    raise RegenError("unbalanced parentheses")


def check_overlay_build(text: str, where: str) -> None:
    """Overlay BUILD files are ours: every rustc_* call must say `vendored = True`."""
    for start, end in _code_spans(text):
        for m in _RUSTC_CALL.finditer(text, start, end):
            close = _matching_paren(text, m.end() - 1)
            if not re.search(r"\bvendored\s*=\s*True\b", text[m.end():close]):
                raise RegenError(f"{where}: {m.group(1)} call without vendored = True")


def rewrite_crate_build(text: str, where: str) -> tuple[str, set[str]]:
    """Rewrite an upstream crate_universe BUILD file for the @rust_crates repository.

    Returns the text and the crate directories (third_party/rust_crates/vendor/<dir>)
    its labels name, so the caller can follow the closure.
    """
    deps: set[str] = set()

    def label(s: str) -> str:
        if not s.startswith("//") or s.startswith(_BUILTIN_PREFIXES):
            return s
        pkg, target = _split_label(s)
        prefix = RUST_CRATES_VENDOR + "/"
        if pkg.startswith(prefix) and "/" not in pkg[len(prefix):]:
            deps.add(pkg[len(prefix):])
            return "//vendor/" + pkg[len(prefix):] + target
        if pkg.startswith(RUST_CRATES):
            raise RegenError(f"{where}: {s}: only crates.io crates from {RUST_CRATES_VENDOR} "
                             "are supported; patched and forked crates come in milestone M6")
        raise RegenError(f"{where}: {s}: unexpected label in a crate_universe BUILD file")

    return _map_strings(text, label), deps


_ALIAS = re.compile(r'alias\(\s*name = "([^"]+)",\s*actual = "([^"]+)",(?:\s*tags = \[[^\]]*\],)?\s*\)')


def parse_aliases(text: str) -> dict[str, str]:
    """name -> actual for each alias() in upstream's third_party/rust_crates/vendor/BUILD.bazel."""
    return {m.group(1): m.group(2) for m in _ALIAS.finditer(text)}


def _package_info(text: str, where: str) -> tuple[str, str]:
    name = re.search(r'package_name = "([^"]+)"', text)
    version = re.search(r'package_version = "([^"]+)"', text)
    if not name or not version:
        raise RegenError(f"{where}: no package_info with package_name and package_version")
    return name.group(1), version.group(1)


def cargo_lock_checksums(text: str) -> dict[tuple[str, str], str]:
    """(name, version) -> SHA-256 for every crates.io package in a Cargo.lock."""
    data = tomllib.loads(text)
    out = {}
    for pkg in data.get("package", []):
        if pkg.get("source") == CRATES_IO_SOURCE and "checksum" in pkg:
            out[(pkg["name"], pkg["version"])] = pkg["checksum"]
    return out


# --- generation ------------------------------------------------------------------


def _header(revision: str, upstream: str, what: str) -> str:
    return (f"# {GENERATED_BY} from fuchsia.git {revision}:{upstream}\n"
            f"# ({what}). Do not edit: change {OVERLAYS}/ or {PATCHES}/ and rerun it.\n")


_VENDOR_ROOT_BUILD = """\
# SPDX-FileCopyrightText: 2026 Curtis Galloway
# SPDX-License-Identifier: Apache-2.0
#
# {generated}. Do not edit.
#
# The license of everything under vendor/fuchsia/, which upstream BUILD files name as
# //:license (fuchsia.git build/bazel/toplevel.BUILD.bazel). Overlay: upstream's kind is
# BSD-2-Clause; its LICENSE text is BSD-3-Clause (LICENSES/BSD-3-Clause.txt).

load("@rules_license//rules:license.bzl", "license")

license(
    name = "license",
    license_kinds = ["@rules_license//licenses/spdx:BSD-3-Clause"],
    license_text = "LICENSE",
    visibility = ["//visibility:public"],
)
"""

_CRATES_BUILD = """\
# SPDX-FileCopyrightText: 2026 Curtis Galloway
# SPDX-License-Identifier: Apache-2.0
#
# {generated}. Do not edit.
#
# //toolchain:crates.bzl reads crates.json and the BUILD.*.bazel files here to create
# the @rust_crates repository (upstream's third_party/rust_crates layout).

exports_files(glob(["BUILD.*.bazel"]) + ["crates.json"])
"""


def _files_of(source: Source, crate: Crate) -> dict[str, int]:
    """The crate's files, without subdirectories that are packages of their own."""
    files = source.files(crate.path)
    subpackages = {str(PurePosixPath(f).parent) for f in files
                   if PurePosixPath(f).name in PACKAGE_FILES and str(PurePosixPath(f).parent) != crate.path}
    return {f: m for f, m in files.items()
            if not any(f.startswith(sp + "/") for sp in subpackages)}


def _write(out: Path, rel: str, data: bytes, mode: int = 0o644) -> None:
    p = out / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_bytes(data)
    p.chmod(mode)


def apply_patches(root: Path, vendor_dir: Path, crates: list[Crate], home: Path) -> list[str]:
    """Apply patches/fuchsia/<path>/*.patch in name order, relative to the fuchsia.git root.

    Returns the applied patches (repo-relative). A patch that does not apply stops the run
    with its name and the file it failed on.
    """
    applied = []
    for crate in crates:
        pdir = root / PATCHES / crate.path
        if not pdir.is_dir():
            continue
        for patch in sorted(pdir.glob("*.patch")):
            rel = patch.relative_to(root).as_posix()
            env = {"GIT_CEILING_DIRECTORIES": str(vendor_dir.parent)}
            try:
                stat_out = isolated_git(vendor_dir, home, "apply", "--numstat", str(patch), extra_env=env)
            except FetchError as e:
                raise RegenError(f"{rel}: not a patch git can read: {e}") from None
            touched = [line.split("\t", 2)[2] for line in stat_out.decode().splitlines() if line]
            outside = [t for t in touched if not t.startswith(crate.path + "/")]
            if outside or not touched:
                raise RegenError(f"{rel}: patches under {PATCHES}/{crate.path}/ may change only files "
                                 f"of {crate.path}; this one changes {', '.join(outside) or 'nothing'}")
            try:
                # GIT_CEILING_DIRECTORIES keeps git from treating an enclosing repository
                # as the one to patch; outside a repository `git apply` works like patch(1).
                isolated_git(vendor_dir, home, "apply", "--whitespace=nowarn", str(patch), extra_env=env)
            except FetchError as e:
                # git's last line names the file: "error: <file>: patch does not apply",
                # "error: <file>: No such file or directory", "error: patch failed: <file>:<n>".
                msg = str(e)
                m = re.search(r"error: (?:patch failed: )?([^:\s]+)", msg)
                failed = m.group(1) if m else "?"
                raise RegenError(f"{rel}: does not apply to {VENDOR_OUT}/{failed}: {msg}") from None
            applied.append(rel)
    return applied


def generate(root: Path, source: Source, out: Path, cargo_lock_sha256: str, home: Path) -> None:
    """Write every output tree (OUTPUTS) under `out`, from `source` and the repo's inputs."""
    crates = read_vendor_list((root / VENDOR_LIST).read_text())
    if not crates:
        raise RegenError(f"{VENDOR_LIST}: lists no crates")
    rev = source.revision
    vendored = {c.path for c in crates}
    vendor = out / VENDOR_OUT
    vendor.mkdir(parents=True)

    crate_files = {c.path: _files_of(source, c) for c in crates}
    # One read, so a GitSource fetches every blob in one request.
    everything = source.read(list(ROOT_FILES) + sorted(f for fs in crate_files.values() for f in fs))
    for name in ROOT_FILES:
        _write(vendor, name, everything[name])
    _write(vendor, "BUILD.bazel", _VENDOR_ROOT_BUILD.format(generated=GENERATED_BY).encode())

    for crate in crates:
        files = crate_files[crate.path]
        build = f"{crate.path}/BUILD.bazel"
        overlay = root / OVERLAYS / crate.path / "BUILD.bazel"
        contents = {f: everything[f] for f in sorted(files)}
        for rel, data in contents.items():
            if rel == build:
                continue
            _write(vendor, rel, data, files[rel])
        if crate.build == "upstream":
            if build not in contents:
                raise RegenError(f"{VENDOR_LIST}: {crate.path} is 'upstream', but upstream has no "
                                 f"BUILD.bazel there; write {OVERLAYS}/{crate.path}/BUILD.bazel "
                                 "and list it as 'overlay'")
            if overlay.exists():
                raise RegenError(f"{OVERLAYS}/{crate.path}/BUILD.bazel exists, but {VENDOR_LIST} "
                                 "says 'upstream'")
            text = rewrite_upstream_build(contents[build].decode(), build, vendored)
            text = _header(rev, build, "labels rewritten, vendored = True added") + text
        else:
            if not overlay.is_file():
                raise RegenError(f"{VENDOR_LIST}: {crate.path} is 'overlay', but "
                                 f"{OVERLAYS}/{crate.path}/BUILD.bazel does not exist")
            text = overlay.read_text()
            check_overlay_build(text, f"{OVERLAYS}/{crate.path}/BUILD.bazel")
        _write(vendor, build, text.encode())

    apply_patches(root, vendor, crates, home)
    generate_crates(vendor, source, out / CRATES_OUT, cargo_lock_sha256)


def generate_crates(vendor: Path, source: Source, out: Path, cargo_lock_sha256: str) -> None:
    """third_party/crates/: the crates.io closure of @rust_crates labels under `vendor`."""
    prefix = f"@{CRATES_REPO}//vendor:"
    roots = {s[len(prefix):] for build in vendor.rglob("BUILD.bazel")
             for s in _strings(build.read_text()) if s.startswith(prefix)}
    out.mkdir(parents=True)
    rev = source.revision
    header_note = "labels rewritten for the @rust_crates repository"
    if not roots:
        crates_json: dict = {"aliases": [], "crates": []}
    else:
        alias_file = f"{RUST_CRATES_VENDOR}/BUILD.bazel"
        texts = source.read([alias_file, CARGO_LOCK])
        lock_sha = hashlib.sha256(texts[CARGO_LOCK]).hexdigest()
        if lock_sha != cargo_lock_sha256:
            raise RegenError(f"{CARGO_LOCK}: SHA-256 {lock_sha} at {rev}, but overlay.lock.json "
                             f"has cargo_lock_sha256 {cargo_lock_sha256}")
        checksums = cargo_lock_checksums(texts[CARGO_LOCK].decode())
        aliases = parse_aliases(texts[alias_file].decode())
        alias_blocks = []
        todo: list[str] = []
        for name in sorted(roots):
            actual = aliases.get(name)
            if actual is None:
                raise RegenError(f"@{CRATES_REPO}//vendor:{name}: upstream {alias_file} has no alias {name!r}")
            text, deps = rewrite_crate_build(f'"{actual}"', alias_file)
            alias_blocks.append(f'alias(\n    name = "{name}",\n    actual = {text},\n)\n')
            todo.extend(sorted(deps))
        seen: set[str] = set()
        entries = []
        frontier = sorted(set(todo))
        while frontier:
            # One read (one blob fetch) per level of the dependency graph.
            seen.update(frontier)
            files = {d: f"{RUST_CRATES_VENDOR}/{d}/BUILD.bazel" for d in frontier}
            raws = source.read(sorted(files.values()))
            nxt: set[str] = set()
            for d in frontier:
                upstream = files[d]
                raw = raws[upstream].decode()
                name, version = _package_info(raw, upstream)
                if d != f"{name}-{version}":
                    raise RegenError(f"{upstream}: package_info says {name} {version}, not {d}")
                sha = checksums.get((name, version))
                if sha is None:
                    raise RegenError(f"{upstream}: {name} {version} is not a crates.io package in {CARGO_LOCK}")
                text, deps = rewrite_crate_build(raw, upstream)
                build_file = f"BUILD.{d}.bazel"
                _write(out, build_file, (_header(rev, upstream, header_note) + text).encode())
                entries.append({
                    "build_file": build_file,
                    "name": name,
                    "path": f"vendor/{d}",
                    "sha256": sha,
                    "strip_prefix": d,
                    "url": CRATE_URL.format(name=name, version=version),
                    "version": version,
                })
                nxt |= deps
            frontier = sorted(nxt - seen)
        entries.sort(key=lambda e: e["path"])
        aliases_text = (_header(rev, alias_file, "only the aliases vendored crates use; " + header_note)
                        + '\npackage(default_visibility = ["//visibility:public"])\n\n'
                        + "\n".join(alias_blocks))
        _write(out, "BUILD.vendor.bazel", aliases_text.encode())
        crates_json = {"aliases": sorted(roots), "crates": entries}
    crates_json = {
        "cargo_lock": f"{FUCHSIA_GIT} {rev}:{CARGO_LOCK}",
        "cargo_lock_sha256": cargo_lock_sha256,
        "vendor_build_file": "BUILD.vendor.bazel" if roots else None,
        **crates_json,
    }
    _write(out, "crates.json", (json.dumps(crates_json, indent=2, sort_keys=True) + "\n").encode())
    _write(out, "BUILD.bazel", _CRATES_BUILD.format(generated=GENERATED_BY).encode())


# --- install and check -----------------------------------------------------------


def _tree(base: Path) -> dict[str, tuple[bytes, bool]]:
    """rel path -> (content, executable) for every file under base."""
    out = {}
    if base.is_dir():
        for p in sorted(base.rglob("*")):
            if p.is_file() or p.is_symlink():
                out[p.relative_to(base).as_posix()] = (
                    p.read_bytes() if p.is_file() else b"<symlink>",
                    bool(p.stat().st_mode & stat.S_IXUSR) if p.is_file() else False)
    return out


def diff_trees(root: Path, generated: Path) -> list[str]:
    """Drift between the repo's output trees and freshly generated ones, one line per file."""
    problems = []
    for rel in OUTPUTS:
        have, want = _tree(root / rel), _tree(generated / rel)
        for f in sorted(set(have) | set(want)):
            path = f"{rel}/{f}"
            if f not in have:
                problems.append(f"{path}: missing (regen.py would create it)")
            elif f not in want:
                problems.append(f"{path}: not generated by regen.py (remove it, or change the inputs)")
            elif have[f][0] != want[f][0]:
                problems.append(f"{path}: content differs from upstream plus overlays and patches")
            elif have[f][1] != want[f][1]:
                problems.append(f"{path}: executable bit differs")
    return problems


def install(root: Path, generated: Path) -> None:
    """Replace each output tree in the repo with the generated one."""
    for rel in OUTPUTS:
        dest = root / rel
        new = dest.with_name(dest.name + ".regen-new")
        old = dest.with_name(dest.name + ".regen-old")
        for p in (new, old):
            if p.exists():
                shutil.rmtree(p)
        shutil.copytree(generated / rel, new)
        if dest.exists():
            dest.rename(old)
        new.rename(dest)
        if old.exists():
            shutil.rmtree(old)


def run(root: Path, check: bool, make_source=None) -> int:
    revision, cargo_sha = read_lock(root)
    with tempfile.TemporaryDirectory(prefix="regen-") as tmp:
        tmp = Path(tmp)
        home = tmp / "home"
        home.mkdir()
        if make_source is None:
            source = GitSource(FUCHSIA_GIT, revision, tmp / "git")
        else:
            source = make_source(revision)
        generated = tmp / "out"
        generate(root, source, generated, cargo_sha, home)
        if check:
            problems = diff_trees(root, generated)
            for p in problems:
                print(f"regen.py --check: {p}", file=sys.stderr)
            if problems:
                print(f"regen.py --check: {len(problems)} file(s) drift from fuchsia.git {revision} "
                      f"plus {OVERLAYS}/ and {PATCHES}/; rerun `scripts/regen.py vendor`",
                      file=sys.stderr)
                return 1
            print(f"regen.py --check: {', '.join(OUTPUTS)} match fuchsia.git {revision}")
            return 0
        install(root, generated)
        print(f"regen.py: wrote {', '.join(OUTPUTS)} from fuchsia.git {revision}")
        return 0


def main(argv: list[str] | None = None, root: Path = ROOT, make_source=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0],
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("stage", nargs="?", choices=["vendor"], default=None,
                        help="the stage to run (only 'vendor' exists so far)")
    parser.add_argument("--check", action="store_true",
                        help="regenerate into a scratch directory and fail on drift")
    args = parser.parse_args(argv)
    if args.stage is None and not args.check:
        parser.error("give a stage ('vendor') or --check")
    try:
        return run(root, args.check, make_source)
    except RegenError as e:
        print(f"regen.py: {e}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
