# SPDX-FileCopyrightText: 2026 Curtis Galloway
# SPDX-License-Identifier: Apache-2.0

"""API levels from a version_history.json (extension `api_levels`, design R3).

Upstream's Rust toolchain reads `all_numbered_api_levels` and `idk_buildable_api_levels`
from `@fuchsia_build_info//:args.bzl`, which GN writes from the source tree's
`sdk/version_history.json`, and its FIDL rules read `runtime_supported_api_levels`. The
overlay has no GN build, so this repository rule writes the same three names to
`@<name>//:args.bzl` from a `version_history.json` file, using the port of upstream's
`get_platform_version.py` in //rules:api_level.bzl.

MODULE.bazel creates `@fuchsia_api_levels` from the IDK's copy (the release's levels,
used by the toolchains) and two test repositories from pinned copies (tests/api_level).

This is a file of its own so that changing it does not refetch the repositories defined
in repositories.bzl (the IDK is 3 GB).
"""

load("//rules:api_level.bzl", "platform_version_from_json")

def _api_levels_repository_impl(rctx):
    # rctx.read() of a label makes the repository depend on the file's content.
    source = str(rctx.attr.version_history)
    levels = platform_version_from_json(rctx.read(rctx.attr.version_history), source = source)
    rctx.file("args.bzl", """\
# Generated by //toolchain:api_levels.bzl from {source}.
# The names match upstream's @fuchsia_build_info//:args.bzl.

all_numbered_api_levels = {all_numbered}

idk_buildable_api_levels = {idk_buildable}

runtime_supported_api_levels = {runtime_supported}
""".format(
        source = source,
        all_numbered = json.encode(levels.all_numbered_api_levels),
        idk_buildable = json.encode(levels.idk_buildable_api_levels),
        runtime_supported = json.encode(levels.runtime_supported_api_levels),
    ))
    rctx.file("BUILD.bazel", 'exports_files(["args.bzl"])\n')

api_levels_repository = repository_rule(
    implementation = _api_levels_repository_impl,
    doc = "Writes args.bzl with the API levels of a version_history.json.",
    attrs = {
        "version_history": attr.label(
            doc = "A version_history.json file (the IDK's, or a pinned copy).",
            allow_single_file = True,
            mandatory = True,
        ),
    },
)

_from_version_history = tag_class(attrs = {
    "name": attr.string(mandatory = True),
    "version_history": attr.label(mandatory = True),
})

def _api_levels_impl(module_ctx):
    for mod in module_ctx.modules:
        for tag in mod.tags.from_version_history:
            api_levels_repository(name = tag.name, version_history = tag.version_history)
    return module_ctx.extension_metadata(reproducible = True)

api_levels = module_extension(
    implementation = _api_levels_impl,
    tag_classes = {"from_version_history": _from_version_history},
)
