# SPDX-FileCopyrightText: 2026 Curtis Galloway
# SPDX-License-Identifier: Apache-2.0

"""`@fuchsia_sdk`, `@fuchsia_clang` and the SDK toolchain declaration (extension `fuchsia_repos`).

These use rules_fuchsia's own repository rules, so this extension loads from
`@rules_fuchsia`, which the `lock_repos` extension (repositories.bzl) creates:

- `fuchsia_sdk` is generated by rules_fuchsia from `@fuchsia_idk`, the release's IDK.
  (The release publishes no prebuilt Bazel SDK; see docs/evidence/M1.md.)
- `fuchsia_clang` is the lock's CIPD instance of clang, which rules_fuchsia downloads by
  instance ID and checks by SHA-256.
"""

load("@rules_fuchsia//fuchsia/workspace:fuchsia_clang_repository.bzl", "fuchsia_clang_repository")
load("@rules_fuchsia//fuchsia/workspace:fuchsia_sdk_repository.bzl", "fuchsia_sdk_repository")
load("@rules_fuchsia//fuchsia/workspace:register_fuchsia_sdk_toolchain.bzl", "fuchsia_toolchain_decl")
load(":lock.bzl", "cipd_instance_id", "cipd_package", "read_lock")

# rules_fuchsia builds the clang URL from this package for a linux-amd64 host (C5).
_CLANG_PACKAGE = "fuchsia/third_party/clang/linux-amd64"

def _fuchsia_repos_impl(module_ctx):
    lock = read_lock(module_ctx)
    clang = cipd_package(lock, "clang")
    if clang.package != _CLANG_PACKAGE:
        fail("overlay.lock.json: clang: package %r, expected %r" % (clang.package, _CLANG_PACKAGE))
    fuchsia_clang_repository(
        name = "fuchsia_clang",
        cipd_tag = cipd_instance_id("clang", clang.sha256),
        sha256 = {"linux": clang.sha256},
    )
    fuchsia_sdk_repository(
        name = "fuchsia_sdk",
        # A label in the IDK's root; rules_fuchsia reads meta/manifest.json next to it.
        local_paths = [str(Label("@fuchsia_idk//:BUILD.bazel"))],
    )
    fuchsia_toolchain_decl(
        name = "fuchsia_sdk_toolchain",
        toolchain_path = "@fuchsia_sdk//:fuchsia_toolchain_info",
    )
    return module_ctx.extension_metadata(reproducible = True)

fuchsia_repos = module_extension(
    implementation = _fuchsia_repos_impl,
    doc = "The Fuchsia SDK and clang repositories, from overlay.lock.json pins.",
)
